import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  PolicyBlock,
  PredicateExpr,
  PrimitiveType,
  TypeExpr,
  ValidationBlock,
} from "@aiparlance/parser";
import { fkColumnName, tableName, toSnakeCase } from "@aiparlance/sql";

export class EmitOpenApiError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitOpenApiError";
  }
}

type JsonSchema = Record<string, unknown>;
type OpenApiDoc = {
  openapi: string;
  info: { title: string; version: string; description?: string };
  paths: Record<string, unknown>;
  components: {
    schemas: Record<string, JsonSchema>;
    securitySchemes?: Record<string, unknown>;
    responses?: Record<string, unknown>;
  };
  security?: Array<Record<string, string[]>>;
  "x-aip-cors"?: { allow: string[] };
  "x-aip-rate-limit"?: { count: number; unit: string };
};

type AuthStrategy = "jwt" | "session" | "api_key" | "oauth";

/**
 * Emit OpenAPI 3.0 JSON from a validated AST.
 * Honors `api.prefix`, `api.cors`, `api.rate_limit`, `app.auth`, and per-operation `policy` rules.
 */
export function emitOpenApi(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitOpenApiError("no entity blocks to emit");
  }

  const crudEntities = new Set(
    doc.blocks
      .filter((b) => b.kind === "Crud")
      .map((b) => (b.kind === "Crud" ? b.entity : ""))
  );

  const policies = new Map<string, PolicyBlock>();
  for (const b of doc.blocks) {
    if (b.kind === "Policy") policies.set(b.entity, b);
  }

  const validations = doc.blocks.filter(
    (b): b is ValidationBlock => b.kind === "Validation"
  );

  const api = doc.blocks.find((b) => b.kind === "Api");
  let pathPrefix = "";
  const corsAllows: string[] = [];
  let rateLimit: { count: number; unit: string } | null = null;
  if (api && api.kind === "Api") {
    for (const m of api.members) {
      if (m.kind === "prefix") pathPrefix = m.value.replace(/\/$/, "");
      if (m.kind === "cors") corsAllows.push(...m.allows);
      if (m.kind === "rate_limit") rateLimit = m.value;
    }
  }

  const version = doc.app.version ?? "0.1.0";
  const out: OpenApiDoc = {
    openapi: "3.0.3",
    info: {
      title: doc.app.name,
      version: version.includes(".") ? version : `${version}.0`,
      description: `Generated by @aiparlance/openapi from ${doc.fileName}. owner_or_manager = owner match OR role admin|editor.`,
    },
    paths: {},
    components: {
      schemas: {
        Error: {
          type: "object",
          required: ["error"],
          properties: {
            error: {
              type: "object",
              required: ["code", "message"],
              properties: {
                code: {
                  type: "string",
                  enum: [
                    "validation",
                    "unauthorized",
                    "forbidden",
                    "not_found",
                    "conflict",
                    "rate_limited",
                    "method_not_allowed",
                    "bad_request",
                  ],
                },
                message: { type: "string" },
                details: {},
              },
            },
          },
        },
        PaginatedList: {
          type: "object",
          required: ["items", "limit", "offset", "total"],
          properties: {
            items: { type: "array", items: {} },
            limit: { type: "integer" },
            offset: { type: "integer" },
            total: { type: "integer" },
          },
        },
      },
      responses: {
        BadRequest: {
          description: "Validation or bad request",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
        NotFound: {
          description: "Not found",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
        Conflict: {
          description: "Unique constraint violated",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
        TooManyRequests: {
          description: "Rate limit exceeded",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
      },
    },
  };

  if (corsAllows.length > 0) {
    out["x-aip-cors"] = { allow: corsAllows };
  }
  if (rateLimit) {
    out["x-aip-rate-limit"] = rateLimit;
  }

  const auth = doc.app.members.find((m) => m.kind === "auth");
  const strategy =
    auth && auth.kind === "auth" ? (auth.strategy as AuthStrategy) : null;

  if (strategy) {
    out.components.securitySchemes = securityScheme(strategy);
    out.components.responses = {
      ...out.components.responses,
      Unauthorized: {
        description: "Authentication required",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
          },
        },
      },
      Forbidden: {
        description: "Authenticated but not allowed by policy",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
          },
        },
      },
    };
    if (policies.size === 0) {
      out.security = securityRequirement(strategy);
    }
  }

  for (const entity of entities) {
    out.components.schemas[entity.name] = entitySchema(entity, "full");
    out.components.schemas[`${entity.name}Create`] = entitySchema(
      entity,
      "create"
    );
    out.components.schemas[`${entity.name}Update`] = entitySchema(
      entity,
      "update"
    );
  }

  for (const entity of entities) {
    if (!crudEntities.has(entity.name)) continue;
    Object.assign(
      out.paths,
      crudPaths(
        entity,
        pathPrefix,
        policies.get(entity.name),
        strategy,
        policies.size > 0,
        validations,
        Boolean(rateLimit)
      )
    );
  }

  return `${JSON.stringify(out, null, 2)}\n`;
}

function securityScheme(
  strategy: AuthStrategy
): Record<string, unknown> {
  switch (strategy) {
    case "jwt":
    case "oauth":
      return {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: strategy === "jwt" ? "JWT" : "OAuth",
        },
      };
    case "api_key":
      return {
        apiKeyAuth: {
          type: "apiKey",
          in: "header",
          name: "X-API-Key",
        },
      };
    case "session":
      return {
        cookieAuth: {
          type: "apiKey",
          in: "cookie",
          name: "session",
        },
      };
  }
}

function securityRequirement(
  strategy: AuthStrategy
): Array<Record<string, string[]>> {
  const key =
    strategy === "jwt" || strategy === "oauth"
      ? "bearerAuth"
      : strategy === "api_key"
        ? "apiKeyAuth"
        : "cookieAuth";
  return [{ [key]: [] }];
}

function schemeKey(strategy: AuthStrategy): string {
  return strategy === "jwt" || strategy === "oauth"
    ? "bearerAuth"
    : strategy === "api_key"
      ? "apiKeyAuth"
      : "cookieAuth";
}

function predicateForAction(
  policy: PolicyBlock | undefined,
  action: string
): PredicateExpr | null {
  if (!policy) return null;
  const rule = policy.rules.find((r) => r.action === action);
  return rule?.predicate ?? null;
}

function opSecurity(
  predicate: PredicateExpr | null,
  strategy: AuthStrategy | null,
  hasAnyPolicy: boolean
): { security?: Array<Record<string, string[]>>; authErrors: boolean } {
  if (!strategy) {
    return { authErrors: false };
  }

  if (!predicate) {
    if (!hasAnyPolicy) {
      return { authErrors: true };
    }
    return {
      security: securityRequirement(strategy),
      authErrors: true,
    };
  }

  if (predicate.kind === "public") {
    return { security: [], authErrors: false };
  }

  const scopes: string[] = [];
  if (predicate.kind === "role") scopes.push(`role:${predicate.name}`);
  if (predicate.kind === "permission")
    scopes.push(`permission:${predicate.name}`);
  if (predicate.kind === "owner_or_manager") {
    scopes.push("role:admin", "role:editor", "owner");
  }
  if (predicate.kind === "owner") scopes.push("owner");

  return {
    security: [{ [schemeKey(strategy)]: scopes }],
    authErrors: true,
  };
}

function withAuthResponses(
  responses: Record<string, unknown>,
  authErrors: boolean
): Record<string, unknown> {
  if (!authErrors) return responses;
  return {
    ...responses,
    "401": { $ref: "#/components/responses/Unauthorized" },
    "403": { $ref: "#/components/responses/Forbidden" },
  };
}

function entityHasUnique(
  entity: EntityBlock,
  validations: ValidationBlock[]
): boolean {
  for (const item of entity.body) {
    if (item.kind === "Field" && item.modifiers.some((m) => m.kind === "unique")) {
      return true;
    }
  }
  return validations.some(
    (v) =>
      v.entity === entity.name &&
      v.rules.some((r) => r.modifiers.includes("unique"))
  );
}

function entitySchema(
  entity: EntityBlock,
  mode: "full" | "create" | "update"
): JsonSchema {
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declared = new Set(fields.map((f) => f.name));

  const properties: Record<string, JsonSchema> = {};
  const required: string[] = [];

  if (mode === "full" && !declared.has("id")) {
    properties.id = { type: "string", format: "uuid", readOnly: true };
    required.push("id");
  }

  for (const field of fields) {
    const name = propertyName(field);
    const prop = fieldToSchema(field.type);
    const isRequired = field.modifiers.some((m) => m.kind === "required");
    const isOptional =
      field.modifiers.some((m) => m.kind === "optional") ||
      (field.type.kind === "BelongsTo" && field.type.optional);

    if (mode === "update") {
      properties[name] = prop;
      continue;
    }

    properties[name] = prop;
    if (mode === "full" || mode === "create") {
      if (isRequired && !isOptional) required.push(name);
    }
  }

  if (mode === "full") {
    if (!declared.has("created_at")) {
      properties.created_at = {
        type: "string",
        format: "date-time",
        readOnly: true,
      };
      required.push("created_at");
    }
    if (!declared.has("updated_at")) {
      properties.updated_at = {
        type: "string",
        format: "date-time",
        readOnly: true,
      };
      required.push("updated_at");
    }
    if (softDelete && !declared.has("deleted_at")) {
      properties.deleted_at = {
        type: "string",
        format: "date-time",
        nullable: true,
        readOnly: true,
      };
    }
  }

  const schema: JsonSchema = {
    type: "object",
    properties,
  };
  if (required.length > 0 && mode !== "update") {
    schema.required = required;
  }
  return schema;
}

function propertyName(field: FieldDecl): string {
  if (field.type.kind === "BelongsTo") return fkColumnName(field.name);
  return toSnakeCase(field.name);
}

function fieldToSchema(type: TypeExpr): JsonSchema {
  switch (type.kind) {
    case "Primitive":
      return primitiveSchema(type.name);
    case "Enum":
      return { type: "string", enum: type.variants };
    case "BelongsTo":
      return { type: "string", format: "uuid" };
    case "EntityRef":
      return { type: "string", format: "uuid" };
  }
}

function primitiveSchema(name: PrimitiveType): JsonSchema {
  switch (name) {
    case "string":
    case "text":
    case "phone":
      return { type: "string" };
    case "email":
      return { type: "string", format: "email" };
    case "int":
      return { type: "integer" };
    case "float":
      return { type: "number" };
    case "bool":
      return { type: "boolean" };
    case "datetime":
      return { type: "string", format: "date-time" };
    case "date":
      return { type: "string", format: "date" };
    case "uuid":
      return { type: "string", format: "uuid" };
    case "json":
      return { type: "object", additionalProperties: true };
  }
}

function crudPaths(
  entity: EntityBlock,
  pathPrefix = "",
  policy: PolicyBlock | undefined,
  strategy: AuthStrategy | null,
  docHasPolicies: boolean,
  validations: ValidationBlock[],
  hasRateLimit: boolean
): Record<string, unknown> {
  const collection = `${pathPrefix}/${tableName(entity.name)}`;
  const item = `${collection}/{id}`;
  const tag = entity.name;
  const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const hasUnique = entityHasUnique(entity, validations);

  const commonErrors = (extra: Record<string, unknown> = {}) => {
    const responses: Record<string, unknown> = {
      ...extra,
      "400": { $ref: "#/components/responses/BadRequest" },
    };
    if (hasRateLimit) {
      responses["429"] = { $ref: "#/components/responses/TooManyRequests" };
    }
    return responses;
  };

  const apply = (action: string, op: Record<string, unknown>) => {
    const pred = predicateForAction(policy, action);
    const { security, authErrors } = opSecurity(
      pred,
      strategy,
      docHasPolicies
    );
    const next = { ...op };
    if (security !== undefined) next.security = security;
    next.responses = withAuthResponses(
      (op.responses as Record<string, unknown>) ?? {},
      authErrors
    );
    if (pred && pred.kind !== "public") {
      next["x-aip-policy"] =
        pred.kind === "owner_or_manager"
          ? `${describePredicate(pred)} (managers: admin|editor)`
          : describePredicate(pred);
    } else if (pred?.kind === "public") {
      next["x-aip-policy"] = "public";
    }
    if (softDelete && (action === "read" || action === "list")) {
      next["x-aip-soft-delete"] = "default reads hide rows with deleted_at set";
    }
    return next;
  };

  return {
    [collection]: {
      get: apply("read", {
        operationId: `list${entity.name}`,
        tags: [tag],
        summary: `List ${tableName(entity.name)}`,
        description: softDelete
          ? "Soft-deleted rows (deleted_at set) are omitted by default."
          : undefined,
        parameters: [
          {
            name: "limit",
            in: "query",
            schema: { type: "integer", minimum: 1, maximum: 100, default: 50 },
          },
          {
            name: "offset",
            in: "query",
            schema: { type: "integer", minimum: 0, default: 0 },
          },
        ],
        responses: commonErrors({
          "200": {
            description: "OK (paginated)",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["items", "limit", "offset", "total"],
                  properties: {
                    items: { type: "array", items: ref(entity.name) },
                    limit: { type: "integer" },
                    offset: { type: "integer" },
                    total: { type: "integer" },
                  },
                },
              },
            },
          },
        }),
      }),
      post: apply("create", {
        operationId: `create${entity.name}`,
        tags: [tag],
        summary: `Create ${entity.name}`,
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: ref(`${entity.name}Create`),
            },
          },
        },
        responses: commonErrors({
          "201": {
            description: "Created",
            content: {
              "application/json": {
                schema: ref(entity.name),
              },
            },
          },
          ...(hasUnique
            ? { "409": { $ref: "#/components/responses/Conflict" } }
            : {}),
        }),
      }),
    },
    [item]: {
      get: apply("read", {
        operationId: `get${entity.name}`,
        tags: [tag],
        summary: `Get ${entity.name}`,
        description: softDelete
          ? "Returns 404 when the row is soft-deleted."
          : undefined,
        parameters: [idParam()],
        responses: commonErrors({
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: ref(entity.name),
              },
            },
          },
          "404": { $ref: "#/components/responses/NotFound" },
        }),
      }),
      put: apply("update", {
        operationId: `update${entity.name}`,
        tags: [tag],
        summary: `Update ${entity.name}`,
        parameters: [idParam()],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: ref(`${entity.name}Update`),
            },
          },
        },
        responses: commonErrors({
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: ref(entity.name),
              },
            },
          },
          "404": { $ref: "#/components/responses/NotFound" },
          ...(hasUnique
            ? { "409": { $ref: "#/components/responses/Conflict" } }
            : {}),
        }),
      }),
      delete: apply("delete", {
        operationId: `delete${entity.name}`,
        tags: [tag],
        summary: `Delete ${entity.name}`,
        parameters: [idParam()],
        responses: commonErrors({
          "204": { description: "No content" },
          "404": { $ref: "#/components/responses/NotFound" },
        }),
      }),
    },
  };
}

function describePredicate(pred: PredicateExpr): string {
  switch (pred.kind) {
    case "public":
      return "public";
    case "authenticated":
      return "authenticated";
    case "role":
      return `role(${pred.name})`;
    case "permission":
      return `permission(${pred.name})`;
    case "owner":
      return `owner(${pred.field.parts.join(".")})`;
    case "owner_or_manager":
      return `owner_or_manager(${pred.field.parts.join(".")})`;
  }
}

function idParam(): Record<string, unknown> {
  return {
    name: "id",
    in: "path",
    required: true,
    schema: { type: "string", format: "uuid" },
  };
}
