import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  PrimitiveType,
  TypeExpr,
} from "@aiparlance/parser";
import { fkColumnName, tableName, toSnakeCase } from "@aiparlance/sql";

export class EmitOpenApiError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitOpenApiError";
  }
}

type JsonSchema = Record<string, unknown>;
type OpenApiDoc = {
  openapi: string;
  info: { title: string; version: string; description?: string };
  paths: Record<string, unknown>;
  components: {
    schemas: Record<string, JsonSchema>;
    securitySchemes?: Record<string, unknown>;
  };
  security?: Array<Record<string, string[]>>;
};

/**
 * Emit OpenAPI 3.0 JSON from a Core AST (Phase C / M4).
 * Assumes the document already passed semantic validation.
 * `api { }` block not parsed yet — paths use `/` root (Syntax CRUD conventions).
 */
export function emitOpenApi(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitOpenApiError("no entity blocks to emit");
  }

  const crudEntities = new Set(
    doc.blocks
      .filter((b) => b.kind === "Crud")
      .map((b) => (b.kind === "Crud" ? b.entity : ""))
  );

  const version = doc.app.version ?? "0.1.0";
  const out: OpenApiDoc = {
    openapi: "3.0.3",
    info: {
      title: doc.app.name,
      version: version.includes(".") ? version : `${version}.0`,
      description: `Generated by @aiparlance/openapi from ${doc.fileName}`,
    },
    paths: {},
    components: { schemas: {} },
  };

  const auth = doc.app.members.find((m) => m.kind === "auth");
  if (auth && auth.kind === "auth") {
    out.components.securitySchemes = securityScheme(auth.strategy);
    out.security = securityRequirement(auth.strategy);
  }

  for (const entity of entities) {
    out.components.schemas[entity.name] = entitySchema(entity, "full");
    out.components.schemas[`${entity.name}Create`] = entitySchema(
      entity,
      "create"
    );
    out.components.schemas[`${entity.name}Update`] = entitySchema(
      entity,
      "update"
    );
  }

  for (const entity of entities) {
    if (!crudEntities.has(entity.name)) continue;
    Object.assign(out.paths, crudPaths(entity));
  }

  return `${JSON.stringify(out, null, 2)}\n`;
}

function securityScheme(
  strategy: "jwt" | "session" | "api_key" | "oauth"
): Record<string, unknown> {
  switch (strategy) {
    case "jwt":
    case "oauth":
      return {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: strategy === "jwt" ? "JWT" : "OAuth",
        },
      };
    case "api_key":
      return {
        apiKeyAuth: {
          type: "apiKey",
          in: "header",
          name: "X-API-Key",
        },
      };
    case "session":
      return {
        cookieAuth: {
          type: "apiKey",
          in: "cookie",
          name: "session",
        },
      };
  }
}

function securityRequirement(
  strategy: "jwt" | "session" | "api_key" | "oauth"
): Array<Record<string, string[]>> {
  const key =
    strategy === "jwt" || strategy === "oauth"
      ? "bearerAuth"
      : strategy === "api_key"
        ? "apiKeyAuth"
        : "cookieAuth";
  return [{ [key]: [] }];
}

function entitySchema(
  entity: EntityBlock,
  mode: "full" | "create" | "update"
): JsonSchema {
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declared = new Set(fields.map((f) => f.name));

  const properties: Record<string, JsonSchema> = {};
  const required: string[] = [];

  if (mode === "full" && !declared.has("id")) {
    properties.id = { type: "string", format: "uuid", readOnly: true };
    required.push("id");
  }

  for (const field of fields) {
    const name = propertyName(field);
    const prop = fieldToSchema(field.type);
    const isRequired = field.modifiers.some((m) => m.kind === "required");
    const isOptional =
      field.modifiers.some((m) => m.kind === "optional") ||
      (field.type.kind === "BelongsTo" && field.type.optional);

    if (mode === "update") {
      properties[name] = prop;
      continue;
    }

    properties[name] = prop;
    if (mode === "full" || mode === "create") {
      if (isRequired && !isOptional) required.push(name);
    }
  }

  if (mode === "full") {
    if (!declared.has("created_at")) {
      properties.created_at = {
        type: "string",
        format: "date-time",
        readOnly: true,
      };
      required.push("created_at");
    }
    if (!declared.has("updated_at")) {
      properties.updated_at = {
        type: "string",
        format: "date-time",
        readOnly: true,
      };
      required.push("updated_at");
    }
    if (softDelete && !declared.has("deleted_at")) {
      properties.deleted_at = {
        type: "string",
        format: "date-time",
        nullable: true,
        readOnly: true,
      };
    }
  }

  const schema: JsonSchema = {
    type: "object",
    properties,
  };
  if (required.length > 0 && mode !== "update") {
    schema.required = required;
  }
  return schema;
}

function propertyName(field: FieldDecl): string {
  if (field.type.kind === "BelongsTo") return fkColumnName(field.name);
  return toSnakeCase(field.name);
}

function fieldToSchema(type: TypeExpr): JsonSchema {
  switch (type.kind) {
    case "Primitive":
      return primitiveSchema(type.name);
    case "Enum":
      return { type: "string", enum: type.variants };
    case "BelongsTo":
      return { type: "string", format: "uuid" };
    case "EntityRef":
      return { type: "string", format: "uuid" };
  }
}

function primitiveSchema(name: PrimitiveType): JsonSchema {
  switch (name) {
    case "string":
    case "text":
    case "phone":
      return { type: "string" };
    case "email":
      return { type: "string", format: "email" };
    case "int":
      return { type: "integer" };
    case "float":
      return { type: "number" };
    case "bool":
      return { type: "boolean" };
    case "datetime":
      return { type: "string", format: "date-time" };
    case "date":
      return { type: "string", format: "date" };
    case "uuid":
      return { type: "string", format: "uuid" };
    case "json":
      return { type: "object", additionalProperties: true };
  }
}

function crudPaths(entity: EntityBlock): Record<string, unknown> {
  const collection = `/${tableName(entity.name)}`;
  const item = `${collection}/{id}`;
  const tag = entity.name;
  const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });

  return {
    [collection]: {
      get: {
        operationId: `list${entity.name}`,
        tags: [tag],
        summary: `List ${tableName(entity.name)}`,
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: ref(entity.name),
                },
              },
            },
          },
        },
      },
      post: {
        operationId: `create${entity.name}`,
        tags: [tag],
        summary: `Create ${entity.name}`,
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: ref(`${entity.name}Create`),
            },
          },
        },
        responses: {
          "201": {
            description: "Created",
            content: {
              "application/json": {
                schema: ref(entity.name),
              },
            },
          },
        },
      },
    },
    [item]: {
      get: {
        operationId: `get${entity.name}`,
        tags: [tag],
        summary: `Get ${entity.name}`,
        parameters: [idParam()],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: ref(entity.name),
              },
            },
          },
          "404": { description: "Not found" },
        },
      },
      put: {
        operationId: `update${entity.name}`,
        tags: [tag],
        summary: `Update ${entity.name}`,
        parameters: [idParam()],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: ref(`${entity.name}Update`),
            },
          },
        },
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: ref(entity.name),
              },
            },
          },
          "404": { description: "Not found" },
        },
      },
      delete: {
        operationId: `delete${entity.name}`,
        tags: [tag],
        summary: `Delete ${entity.name}`,
        parameters: [idParam()],
        responses: {
          "204": { description: "No content" },
          "404": { description: "Not found" },
        },
      },
    },
  };
}

function idParam(): Record<string, unknown> {
  return {
    name: "id",
    in: "path",
    required: true,
    schema: { type: "string", format: "uuid" },
  };
}
