/** Generated by @aiparlance/typescript from examples/minimal.aip — do not edit by hand. */
import { z } from "zod";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { randomUUID } from "node:crypto";

export interface User {
  id: string;
  name: string;
  email: string;
  created_at: string;
  updated_at: string;
}

export interface UserCreate {
  name: string;
  email: string;
}

export interface UserUpdate {
  name?: string;
  email?: string;
}

export function isUser(value: unknown): value is User {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.id === "string" &&
    typeof v.name === "string" &&
    typeof v.email === "string" &&
    typeof v.created_at === "string" &&
    typeof v.updated_at === "string"
  );
}

export function isUserCreate(value: unknown): value is UserCreate {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.name === "string" &&
    typeof v.email === "string"
  );
}

export const UserCreateSchema = z.object({
  name: z.string(),
  email: z.string().email(),
});
export const UserUpdateSchema = z.object({
  name: z.string().optional(),
  email: z.string().email().optional(),
});
export const UserSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  email: z.string().email(),
  created_at: z.string().datetime({ offset: true }).or(z.string()),
  updated_at: z.string().datetime({ offset: true }).or(z.string()),
});

/** Thin typed CRUD path helpers for User. */
export const userPaths = {
  collection: "/users",
  item: (id: string) => `/users/${id}` as const,
} as const;

/** In-memory CRUD actor (Preview). Pass Bearer + optional x-aip-user-id / x-aip-role. */
export type CrudActor = {
  authenticated: boolean;
  id?: string;
  role?: string;
};

const __aipResources = {
  "users": {
    createSchema: UserCreateSchema,
    updateSchema: UserUpdateSchema,
    softDelete: false,
    policy: {} as Record<string, string>,
    ownerField: null,
  }
} as const;

type __AipResourceName = keyof typeof __aipResources;

const __aipStore = new Map<__AipResourceName, Map<string, Record<string, unknown>>>();
for (const name of Object.keys(__aipResources) as __AipResourceName[]) {
  __aipStore.set(name, new Map());
}

function __aipActor(req: IncomingMessage): CrudActor {
  const auth = req.headers.authorization;
  const authenticated = Boolean(auth && String(auth).toLowerCase().startsWith("bearer "));
  const idHeader = req.headers["x-aip-user-id"];
  const roleHeader = req.headers["x-aip-role"];
  return {
    authenticated,
    id: typeof idHeader === "string" ? idHeader : undefined,
    role: typeof roleHeader === "string" ? roleHeader : undefined,
  };
}

function __aipAllow(policy: string | undefined, actor: CrudActor, row?: Record<string, unknown>, ownerField?: string | null): boolean {
  if (!policy || policy === "public") return true;
  if (policy === "authenticated") return actor.authenticated;
  if (policy.startsWith("role(")) {
    const role = policy.slice(5, -1);
    return actor.authenticated && actor.role === role;
  }
  if (policy.startsWith("permission(")) {
    return actor.authenticated;
  }
  if (policy.startsWith("owner") && ownerField && row) {
    if (!actor.authenticated || !actor.id) return false;
    return row[ownerField] === actor.id;
  }
  return true;
}

function __aipReadBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
    req.on("end", () => {
      const raw = Buffer.concat(chunks).toString("utf8");
      if (!raw) return resolve({});
      try {
        resolve(JSON.parse(raw));
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });
}

function __aipJson(res: ServerResponse, status: number, body: unknown): void {
  const data = body === undefined ? "" : JSON.stringify(body);
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "access-control-allow-origin": "*",
    "access-control-allow-headers": "authorization, content-type, x-aip-user-id, x-aip-role",
    "access-control-allow-methods": "GET,POST,PUT,DELETE,OPTIONS",
  });
  res.end(data);
}

/**
 * Thin runnable CRUD app (in-memory). Prefix: /.
 * Auth: Authorization Bearer + optional x-aip-user-id / x-aip-role headers.
 */
export function createCrudApp(): ReturnType<typeof createServer> {
  const prefix: string = "";
  return createServer(async (req, res) => {
    try {
      if (req.method === "OPTIONS") {
        __aipJson(res, 204, undefined);
        return;
      }
      const url = new URL(req.url ?? "/", "http://localhost");
      let pathname = url.pathname;
      if (prefix.length > 0 && pathname.startsWith(prefix)) {
        pathname = pathname.slice(prefix.length) || "/";
      }
      const parts = pathname.split("/").filter(Boolean);
      if (parts.length === 0 || parts.length > 2) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }
      const resource = parts[0] as __AipResourceName;
      const meta = __aipResources[resource];
      if (!meta) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }
      const store = __aipStore.get(resource)!;
      const actor = __aipActor(req);
      const id = parts[1];
      const method = req.method ?? "GET";

      if (method === "GET" && !id) {
        if (!__aipAllow(meta.policy.read ?? meta.policy.list, actor)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        const rows = [...store.values()].filter((row) =>
          meta.softDelete ? row.deleted_at == null : true
        );
        __aipJson(res, 200, rows);
        return;
      }

      if (method === "POST" && !id) {
        if (!__aipAllow(meta.policy.create, actor)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        const body = await __aipReadBody(req);
        const parsed = meta.createSchema.safeParse(body);
        if (!parsed.success) {
          __aipJson(res, 400, { error: "validation_failed", details: parsed.error.flatten() });
          return;
        }
        const now = new Date().toISOString();
        const row: Record<string, unknown> = {
          id: randomUUID(),
          ...parsed.data,
          created_at: now,
          updated_at: now,
          ...(meta.softDelete ? { deleted_at: null } : {}),
        };
        store.set(String(row.id), row);
        __aipJson(res, 201, row);
        return;
      }

      if (!id) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }

      const existing = store.get(id);
      if (!existing || (meta.softDelete && existing.deleted_at != null && method === "GET")) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }

      if (method === "GET") {
        if (!__aipAllow(meta.policy.read, actor, existing, meta.ownerField)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        __aipJson(res, 200, existing);
        return;
      }

      if (method === "PUT") {
        if (!__aipAllow(meta.policy.update, actor, existing, meta.ownerField)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        const body = await __aipReadBody(req);
        const parsed = meta.updateSchema.safeParse(body);
        if (!parsed.success) {
          __aipJson(res, 400, { error: "validation_failed", details: parsed.error.flatten() });
          return;
        }
        const row = {
          ...existing,
          ...parsed.data,
          updated_at: new Date().toISOString(),
        };
        store.set(id, row);
        __aipJson(res, 200, row);
        return;
      }

      if (method === "DELETE") {
        if (!__aipAllow(meta.policy.delete, actor, existing, meta.ownerField)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        if (meta.softDelete) {
          store.set(id, {
            ...existing,
            deleted_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          });
        } else {
          store.delete(id);
        }
        res.writeHead(204, {
          "access-control-allow-origin": "*",
        });
        res.end();
        return;
      }

      __aipJson(res, 405, { error: "method_not_allowed" });
    } catch {
      __aipJson(res, 400, { error: "bad_request" });
    }
  });
}

/** Listen helper — `PORT` env or 3000. */
export function listenCrudApp(port = Number(process.env.PORT ?? 3000)): void {
  const server = createCrudApp();
  server.listen(port, () => {
    console.log(`AI Parlance CRUD listening on http://127.0.0.1:${port}`);
  });
}
