/** Generated by @aiparlance/typescript from examples/minimal.aip — do not edit by hand. */
/** Env: PORT (default 3000), DATABASE_URL (Postgres), AIP_JWT_SECRET (JWT HS256). */
import { z } from "zod";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { randomUUID } from "node:crypto";
import pg from "pg";
import * as jose from "jose";

export interface User {
  id: string;
  name: string;
  email: string;
  created_at: string;
  updated_at: string;
}

export interface UserCreate {
  name: string;
  email: string;
}

export interface UserUpdate {
  name?: string;
  email?: string;
}

export function isUser(value: unknown): value is User {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.id === "string" &&
    typeof v.name === "string" &&
    typeof v.email === "string" &&
    typeof v.created_at === "string" &&
    typeof v.updated_at === "string"
  );
}

export function isUserCreate(value: unknown): value is UserCreate {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.name === "string" &&
    typeof v.email === "string"
  );
}

export const UserCreateSchema = z.object({
  name: z.string(),
  email: z.string().email(),
});
export const UserUpdateSchema = z.object({
  name: z.string().optional(),
  email: z.string().email().optional(),
});
export const UserSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  email: z.string().email(),
  created_at: z.string().datetime({ offset: true }).or(z.string()),
  updated_at: z.string().datetime({ offset: true }).or(z.string()),
});

/** Thin typed CRUD path helpers for User. */
export const userPaths = {
  collection: "/users",
  item: (id: string) => `/users/${id}` as const,
} as const;

/** Request actor after auth. */
export type CrudActor = {
  authenticated: boolean;
  id?: string;
  role?: string;
};

export type CrudAppOptions = {
  /** Force store. Default: `pg` when DATABASE_URL is set, else `memory`. */
  store?: "memory" | "pg";
  /** HS256 secret. Default: process.env.AIP_JWT_SECRET. */
  jwtSecret?: string;
  databaseUrl?: string;
};

const __aipResources = {
  "users": {
    createSchema: UserCreateSchema,
    updateSchema: UserUpdateSchema,
    softDelete: false,
    policy: {} as Record<string, string>,
    ownerField: null,
    uniqueFields: ["email"] as readonly string[],
  }
} as const;

type __AipResourceName = keyof typeof __aipResources;

const __aipCorsAllows: readonly string[] = [];
const __aipRateLimit: { count: number; windowMs: number } | null = null;
const __aipManagerRoles = new Set(["admin", "editor"]);

const __aipMem = new Map<__AipResourceName, Map<string, Record<string, unknown>>>();
for (const name of Object.keys(__aipResources) as __AipResourceName[]) {
  __aipMem.set(name, new Map());
}

let __aipPool: pg.Pool | null = null;
const __aipRateBuckets = new Map<string, { count: number; resetAt: number }>();

function __aipUsePg(opts?: CrudAppOptions): boolean {
  const mode = opts?.store ?? (process.env.DATABASE_URL ? "pg" : "memory");
  return mode === "pg";
}

function __aipPoolOrThrow(opts?: CrudAppOptions): pg.Pool {
  if (__aipPool) return __aipPool;
  const url = opts?.databaseUrl ?? process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL is required for store: pg");
  }
  __aipPool = new pg.Pool({ connectionString: url });
  return __aipPool;
}

function __aipCorsOrigin(req: IncomingMessage): string | null {
  if (__aipCorsAllows.length === 0) return null;
  const origin = req.headers.origin;
  if (typeof origin !== "string") return null;
  return __aipCorsAllows.includes(origin) ? origin : null;
}

function __aipCorsHeaders(req: IncomingMessage): Record<string, string> {
  const allowed = __aipCorsOrigin(req);
  if (!allowed) return {};
  return {
    "access-control-allow-origin": allowed,
    "access-control-allow-headers": "authorization, content-type, x-aip-user-id, x-aip-role",
    "access-control-allow-methods": "GET,POST,PUT,DELETE,OPTIONS",
    vary: "Origin",
  };
}

function __aipError(code: string, message: string, details?: unknown): { error: { code: string; message: string; details?: unknown } } {
  return details === undefined
    ? { error: { code, message } }
    : { error: { code, message, details } };
}

function __aipJson(req: IncomingMessage, res: ServerResponse, status: number, body: unknown): void {
  const data = body === undefined ? "" : JSON.stringify(body);
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    ...__aipCorsHeaders(req),
  });
  res.end(data);
}

function __aipRateLimited(req: IncomingMessage): boolean {
  if (!__aipRateLimit) return false;
  const key = req.socket.remoteAddress ?? "unknown";
  const now = Date.now();
  let bucket = __aipRateBuckets.get(key);
  if (!bucket || now >= bucket.resetAt) {
    bucket = { count: 0, resetAt: now + __aipRateLimit.windowMs };
    __aipRateBuckets.set(key, bucket);
  }
  bucket.count += 1;
  return bucket.count > __aipRateLimit.count;
}

async function __aipActor(req: IncomingMessage, opts?: CrudAppOptions): Promise<CrudActor> {
  const header = req.headers.authorization;
  if (!header || !String(header).toLowerCase().startsWith("bearer ")) {
    return { authenticated: false };
  }
  const token = String(header).slice(7).trim();
  const secret = opts?.jwtSecret ?? process.env.AIP_JWT_SECRET;
  if (secret) {
    try {
      const { payload } = await jose.jwtVerify(
        token,
        new TextEncoder().encode(secret)
      );
      const id =
        typeof payload.sub === "string"
          ? payload.sub
          : typeof payload.id === "string"
            ? payload.id
            : undefined;
      const role =
        typeof payload.role === "string" ? payload.role : undefined;
      return { authenticated: true, id, role };
    } catch {
      return { authenticated: false };
    }
  }
  // Preview fallback without AIP_JWT_SECRET: any Bearer + optional x-aip-* headers.
  const idHeader = req.headers["x-aip-user-id"];
  const roleHeader = req.headers["x-aip-role"];
  return {
    authenticated: true,
    id: typeof idHeader === "string" ? idHeader : undefined,
    role: typeof roleHeader === "string" ? roleHeader : undefined,
  };
}

function __aipAllow(policy: string | undefined, actor: CrudActor, row?: Record<string, unknown>, ownerField?: string | null): boolean {
  if (!policy || policy === "public") return true;
  if (policy === "authenticated") return actor.authenticated;
  if (policy.startsWith("role(")) {
    const role = policy.slice(5, -1);
    return actor.authenticated && actor.role === role;
  }
  if (policy.startsWith("permission(")) {
    return actor.authenticated;
  }
  if (policy.startsWith("owner_or_manager") && ownerField && row) {
    if (!actor.authenticated) return false;
    if (actor.role && __aipManagerRoles.has(actor.role)) return true;
    return Boolean(actor.id && row[ownerField] === actor.id);
  }
  if (policy.startsWith("owner") && ownerField && row) {
    if (!actor.authenticated || !actor.id) return false;
    return row[ownerField] === actor.id;
  }
  return true;
}

function __aipReadBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
    req.on("end", () => {
      const raw = Buffer.concat(chunks).toString("utf8");
      if (!raw) return resolve({});
      try {
        resolve(JSON.parse(raw));
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });
}

async function __aipList(resource: __AipResourceName, softDelete: boolean, opts?: CrudAppOptions): Promise<Record<string, unknown>[]> {
  if (!__aipUsePg(opts)) {
    return [...__aipMem.get(resource)!.values()].filter((row) =>
      softDelete ? row.deleted_at == null : true
    );
  }
  const pool = __aipPoolOrThrow(opts);
  const where = softDelete ? " WHERE deleted_at IS NULL" : "";
  const { rows } = await pool.query(`SELECT * FROM ${resource}${where}`);
  return rows as Record<string, unknown>[];
}

async function __aipGet(resource: __AipResourceName, id: string, softDelete: boolean, opts?: CrudAppOptions): Promise<Record<string, unknown> | null> {
  if (!__aipUsePg(opts)) {
    const row = __aipMem.get(resource)!.get(id);
    if (!row) return null;
    if (softDelete && row.deleted_at != null) return null;
    return row;
  }
  const pool = __aipPoolOrThrow(opts);
  const where = softDelete
    ? "WHERE id = $1 AND deleted_at IS NULL"
    : "WHERE id = $1";
  const { rows } = await pool.query(`SELECT * FROM ${resource} ${where}`, [id]);
  return (rows[0] as Record<string, unknown>) ?? null;
}

class __AipConflictError extends Error {
  constructor(message = "unique constraint violated") {
    super(message);
    this.name = "ConflictError";
  }
}

async function __aipAssertUnique(
  resource: __AipResourceName,
  uniqueFields: readonly string[],
  data: Record<string, unknown>,
  excludeId: string | null,
  softDelete: boolean,
  opts?: CrudAppOptions
): Promise<void> {
  if (uniqueFields.length === 0) return;
  const rows = await __aipList(resource, softDelete, opts);
  for (const field of uniqueFields) {
    if (!(field in data) || data[field] === undefined) continue;
    const hit = rows.find(
      (row) =>
        row[field] === data[field] &&
        (excludeId == null || String(row.id) !== excludeId)
    );
    if (hit) throw new __AipConflictError(`unique ${field}`);
  }
}

async function __aipInsert(resource: __AipResourceName, row: Record<string, unknown>, opts?: CrudAppOptions): Promise<Record<string, unknown>> {
  if (!__aipUsePg(opts)) {
    __aipMem.get(resource)!.set(String(row.id), row);
    return row;
  }
  const pool = __aipPoolOrThrow(opts);
  const cols = Object.keys(row);
  const vals = cols.map((c) => row[c]);
  const placeholders = cols.map((_, i) => `$${i + 1}`);
  try {
    const { rows } = await pool.query(
      `INSERT INTO ${resource} (${cols.join(", ")}) VALUES (${placeholders.join(", ")}) RETURNING *`,
      vals
    );
    return rows[0] as Record<string, unknown>;
  } catch (err) {
    const code = err && typeof err === "object" && "code" in err ? String((err as { code: unknown }).code) : "";
    if (code === "23505") throw new __AipConflictError();
    throw err;
  }
}

async function __aipUpdate(resource: __AipResourceName, id: string, patch: Record<string, unknown>, opts?: CrudAppOptions): Promise<Record<string, unknown> | null> {
  if (!__aipUsePg(opts)) {
    const store = __aipMem.get(resource)!;
    const existing = store.get(id);
    if (!existing) return null;
    const row = { ...existing, ...patch };
    store.set(id, row);
    return row;
  }
  const pool = __aipPoolOrThrow(opts);
  const cols = Object.keys(patch);
  if (cols.length === 0) return __aipGet(resource, id, false, opts);
  const sets = cols.map((c, i) => `${c} = $${i + 1}`);
  const vals = [...cols.map((c) => patch[c]), id];
  try {
    const { rows } = await pool.query(
      `UPDATE ${resource} SET ${sets.join(", ")} WHERE id = $${cols.length + 1} RETURNING *`,
      vals
    );
    return (rows[0] as Record<string, unknown>) ?? null;
  } catch (err) {
    const code = err && typeof err === "object" && "code" in err ? String((err as { code: unknown }).code) : "";
    if (code === "23505") throw new __AipConflictError();
    throw err;
  }
}

async function __aipDelete(resource: __AipResourceName, id: string, softDelete: boolean, opts?: CrudAppOptions): Promise<boolean> {
  if (!__aipUsePg(opts)) {
    const store = __aipMem.get(resource)!;
    const existing = store.get(id);
    if (!existing) return false;
    if (softDelete) {
      store.set(id, {
        ...existing,
        deleted_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      });
    } else {
      store.delete(id);
    }
    return true;
  }
  const pool = __aipPoolOrThrow(opts);
  if (softDelete) {
    const { rowCount } = await pool.query(
      `UPDATE ${resource} SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL`,
      [id]
    );
    return (rowCount ?? 0) > 0;
  }
  const { rowCount } = await pool.query(`DELETE FROM ${resource} WHERE id = $1`, [id]);
  return (rowCount ?? 0) > 0;
}

/**
 * Thin runnable CRUD app.
 * - Store: Postgres when `DATABASE_URL` (or `opts.store: "pg"`), else in-memory.
 * - Auth: JWT HS256 when `AIP_JWT_SECRET` (claims `sub`/`id`, `role`); else Bearer + x-aip-* Preview headers.
 * - owner_or_manager: owner match OR role admin|editor.
 * - Prefix: /.
 * - Env: PORT, DATABASE_URL, AIP_JWT_SECRET.
 */
export function createCrudApp(opts?: CrudAppOptions): ReturnType<typeof createServer> {
  const prefix: string = "";
  if (__aipUsePg(opts)) {
    __aipPoolOrThrow(opts);
  }
  return createServer(async (req, res) => {
    try {
      if (req.method === "OPTIONS") {
        const cors = __aipCorsHeaders(req);
        if (__aipCorsAllows.length > 0 && !("access-control-allow-origin" in cors)) {
          res.writeHead(403, { "content-type": "application/json; charset=utf-8" });
          res.end(JSON.stringify(__aipError("forbidden", "CORS origin not allowed")));
          return;
        }
        res.writeHead(204, cors);
        res.end();
        return;
      }
      if (__aipRateLimited(req)) {
        __aipJson(req, res, 429, __aipError("rate_limited", "Too many requests"));
        return;
      }
      const url = new URL(req.url ?? "/", "http://localhost");
      let pathname = url.pathname;
      if (prefix.length > 0 && pathname.startsWith(prefix)) {
        pathname = pathname.slice(prefix.length) || "/";
      }
      if (pathname === "/health" || pathname === "/healthz") {
        __aipJson(req, res, 200, { ok: true });
        return;
      }
      const parts = pathname.split("/").filter(Boolean);
      if (parts.length === 0 || parts.length > 2) {
        __aipJson(req, res, 404, __aipError("not_found", "Not found"));
        return;
      }
      const resource = parts[0] as __AipResourceName;
      const meta = __aipResources[resource];
      if (!meta) {
        __aipJson(req, res, 404, __aipError("not_found", "Not found"));
        return;
      }
      const actor = await __aipActor(req, opts);
      const id = parts[1];
      const method = req.method ?? "GET";

      if (method === "GET" && !id) {
        if (!__aipAllow(meta.policy.read ?? meta.policy.list, actor)) {
          __aipJson(req, res, actor.authenticated ? 403 : 401, __aipError(actor.authenticated ? "forbidden" : "unauthorized", "Not allowed"));
          return;
        }
        const limitRaw = Number(url.searchParams.get("limit") ?? 50);
        const offsetRaw = Number(url.searchParams.get("offset") ?? 0);
        const limit = Number.isFinite(limitRaw) ? Math.min(Math.max(limitRaw, 1), 100) : 50;
        const offset = Number.isFinite(offsetRaw) ? Math.max(offsetRaw, 0) : 0;
        const rows = await __aipList(resource, meta.softDelete, opts);
        __aipJson(req, res, 200, {
          items: rows.slice(offset, offset + limit),
          limit,
          offset,
          total: rows.length,
        });
        return;
      }

      if (method === "POST" && !id) {
        if (!__aipAllow(meta.policy.create, actor)) {
          __aipJson(req, res, actor.authenticated ? 403 : 401, __aipError(actor.authenticated ? "forbidden" : "unauthorized", "Not allowed"));
          return;
        }
        const body = await __aipReadBody(req);
        const parsed = meta.createSchema.safeParse(body);
        if (!parsed.success) {
          __aipJson(req, res, 400, __aipError("validation", "Validation failed", parsed.error.flatten()));
          return;
        }
        await __aipAssertUnique(resource, meta.uniqueFields, parsed.data as Record<string, unknown>, null, meta.softDelete, opts);
        const now = new Date().toISOString();
        const row: Record<string, unknown> = {
          id: randomUUID(),
          ...parsed.data,
          created_at: now,
          updated_at: now,
          ...(meta.softDelete ? { deleted_at: null } : {}),
        };
        __aipJson(req, res, 201, await __aipInsert(resource, row, opts));
        return;
      }

      if (!id) {
        __aipJson(req, res, 404, __aipError("not_found", "Not found"));
        return;
      }

      const existing = await __aipGet(resource, id, meta.softDelete && method === "GET", opts);
      if (!existing) {
        __aipJson(req, res, 404, __aipError("not_found", "Not found"));
        return;
      }

      if (method === "GET") {
        if (!__aipAllow(meta.policy.read, actor, existing, meta.ownerField)) {
          __aipJson(req, res, actor.authenticated ? 403 : 401, __aipError(actor.authenticated ? "forbidden" : "unauthorized", "Not allowed"));
          return;
        }
        __aipJson(req, res, 200, existing);
        return;
      }

      if (method === "PUT") {
        if (!__aipAllow(meta.policy.update, actor, existing, meta.ownerField)) {
          __aipJson(req, res, actor.authenticated ? 403 : 401, __aipError(actor.authenticated ? "forbidden" : "unauthorized", "Not allowed"));
          return;
        }
        const body = await __aipReadBody(req);
        const parsed = meta.updateSchema.safeParse(body);
        if (!parsed.success) {
          __aipJson(req, res, 400, __aipError("validation", "Validation failed", parsed.error.flatten()));
          return;
        }
        await __aipAssertUnique(resource, meta.uniqueFields, parsed.data as Record<string, unknown>, id, meta.softDelete, opts);
        const row = await __aipUpdate(
          resource,
          id,
          { ...parsed.data, updated_at: new Date().toISOString() },
          opts
        );
        __aipJson(req, res, 200, row);
        return;
      }

      if (method === "DELETE") {
        if (!__aipAllow(meta.policy.delete, actor, existing, meta.ownerField)) {
          __aipJson(req, res, actor.authenticated ? 403 : 401, __aipError(actor.authenticated ? "forbidden" : "unauthorized", "Not allowed"));
          return;
        }
        const ok = await __aipDelete(resource, id, meta.softDelete, opts);
        if (!ok) {
          __aipJson(req, res, 404, __aipError("not_found", "Not found"));
          return;
        }
        res.writeHead(204, __aipCorsHeaders(req));
        res.end();
        return;
      }

      __aipJson(req, res, 405, __aipError("method_not_allowed", "Method not allowed"));
    } catch (err) {
      if (err instanceof __AipConflictError) {
        __aipJson(req, res, 409, __aipError("conflict", err.message));
        return;
      }
      const message = err instanceof Error ? err.message : "bad_request";
      __aipJson(req, res, 400, __aipError("bad_request", message));
    }
  });
}

/** Sign a Preview JWT (HS256). Requires AIP_JWT_SECRET or `secret`. */
export async function signCrudToken(
  claims: { sub: string; role?: string },
  secret = process.env.AIP_JWT_SECRET
): Promise<string> {
  if (!secret) throw new Error("AIP_JWT_SECRET is required to sign tokens");
  return new jose.SignJWT({ role: claims.role })
    .setProtectedHeader({ alg: "HS256" })
    .setSubject(claims.sub)
    .setIssuedAt()
    .setExpirationTime("12h")
    .sign(new TextEncoder().encode(secret));
}

/** Listen helper — `PORT` env or 3000. Also uses DATABASE_URL / AIP_JWT_SECRET. */
export function listenCrudApp(
  port = Number(process.env.PORT ?? 3000),
  opts?: CrudAppOptions
): void {
  const server = createCrudApp(opts);
  server.listen(port, () => {
    const mode = __aipUsePg(opts) ? "pg" : "memory";
    console.log(`AI Parlance CRUD (${mode}) on http://127.0.0.1:${port}`);
  });
}
