import type { AipDocument, EntityBlock } from "@aiparlance/parser";
import { tableName } from "@aiparlance/sql";

export class EmitTestsError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitTestsError";
  }
}

/**
 * Emit Vitest-style CRUD case fixtures per entity with a \`crud\` declaration.
 */
export function emitTests(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitTestsError("no entity blocks to emit");
  }

  const crudEntities = new Set(
    doc.blocks
      .filter((b) => b.kind === "Crud")
      .map((b) => (b.kind === "Crud" ? b.entity : ""))
  );

  let pathPrefix = "";
  const api = doc.blocks.find((b) => b.kind === "Api");
  if (api && api.kind === "Api") {
    const prefix = api.members.find((m) => m.kind === "prefix");
    if (prefix && prefix.kind === "prefix") {
      pathPrefix = prefix.value.replace(/\/$/, "");
    }
  }

  const lines: string[] = [
    `/** Generated by @aiparlance/tests from ${doc.fileName} — do not edit by hand. */`,
    `/** Vitest-style CRUD fixtures for ${doc.app.name}. */`,
    ``,
    `export type CrudCase = {`,
    `  name: string;`,
    `  method: "GET" | "POST" | "PUT" | "DELETE";`,
    `  path: string;`,
    `};`,
    ``,
  ];

  const withCrud = entities.filter((e) => crudEntities.has(e.name));

  if (withCrud.length === 0) {
    lines.push(`/** No \`crud\` declarations — empty fixture map. */`);
    lines.push(`export const crudCases = {} as const;`);
    lines.push(``);
    return lines.join("\n");
  }

  for (const entity of withCrud) {
    const collection = `${pathPrefix}/${tableName(entity.name)}`;
    const item = `${collection}/{id}`;
    const key = lcFirst(entity.name);
    lines.push(`export const ${key}CrudCases: CrudCase[] = [`);
    lines.push(
      `  { name: "list", method: "GET", path: ${JSON.stringify(collection)} },`
    );
    lines.push(
      `  { name: "create", method: "POST", path: ${JSON.stringify(collection)} },`
    );
    lines.push(
      `  { name: "get", method: "GET", path: ${JSON.stringify(item)} },`
    );
    lines.push(
      `  { name: "update", method: "PUT", path: ${JSON.stringify(item)} },`
    );
    lines.push(
      `  { name: "delete", method: "DELETE", path: ${JSON.stringify(item)} },`
    );
    lines.push(`];`);
    lines.push(``);
  }

  lines.push(`export const crudCases = {`);
  for (const entity of withCrud) {
    const key = lcFirst(entity.name);
    lines.push(`  ${key}: ${key}CrudCases,`);
  }
  lines.push(`} as const;`);
  lines.push(``);

  return lines.join("\n");
}

function lcFirst(name: string): string {
  if (!name) return name;
  return name[0]!.toLowerCase() + name.slice(1);
}
