import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  TypeExpr,
} from "@aiparlance/parser";
import { fkColumnName, quoteIdent, tableName } from "./naming.js";
import { formatDefault, sqlType } from "./types.js";

export class EmitSqlError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitSqlError";
  }
}

/**
 * Emit PostgreSQL DDL from a Core AST (Phase C / M3).
 * Assumes the document already passed semantic validation.
 */
export function emitSql(doc: AipDocument): string {
  const db = doc.app.members.find((m) => m.kind === "database");
  if (!db || db.kind !== "database") {
    throw new EmitSqlError("app.database is required to emit SQL");
  }
  if (db.engine !== "postgres") {
    throw new EmitSqlError(
      `SQL emitter M3 supports postgres only (got '${db.engine}')`
    );
  }

  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitSqlError("no entity blocks to emit");
  }

  const ordered = orderEntities(entities);
  const lines: string[] = [
    `-- Generated by @aiparlance/sql (PostgreSQL)`,
    `-- App: ${doc.app.name}${doc.app.version ? ` @${doc.app.version}` : ""}`,
    `-- Source: ${doc.fileName}`,
    ``,
    `CREATE EXTENSION IF NOT EXISTS pgcrypto;`,
    ``,
  ];

  for (const entity of ordered) {
    lines.push(...emitCreateTable(entity));
    lines.push(``);
  }

  return lines.join("\n").replace(/\n+$/, "\n");
}

function orderEntities(entities: EntityBlock[]): EntityBlock[] {
  const byName = new Map(entities.map((e) => [e.name, e]));
  const deps = new Map<string, Set<string>>();

  for (const e of entities) {
    const needs = new Set<string>();
    for (const item of e.body) {
      if (item.kind !== "Field") continue;
      if (item.type.kind === "BelongsTo" && byName.has(item.type.entity)) {
        if (item.type.entity !== e.name) needs.add(item.type.entity);
      }
    }
    deps.set(e.name, needs);
  }

  const result: EntityBlock[] = [];
  const visiting = new Set<string>();
  const done = new Set<string>();

  function visit(name: string): void {
    if (done.has(name)) return;
    if (visiting.has(name)) {
      throw new EmitSqlError(
        `cyclic belongs_to involving entity '${name}'`
      );
    }
    visiting.add(name);
    for (const dep of deps.get(name) ?? []) visit(dep);
    visiting.delete(name);
    done.add(name);
    const entity = byName.get(name);
    if (entity) result.push(entity);
  }

  for (const e of entities) visit(e.name);
  return result;
}

function emitCreateTable(entity: EntityBlock): string[] {
  const table = quoteIdent(tableName(entity.name));
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declaredNames = new Set(fields.map((f) => f.name));

  const cols: string[] = [];
  const checks: string[] = [];

  if (!declaredNames.has("id")) {
    cols.push(
      `  ${quoteIdent("id")} UUID PRIMARY KEY DEFAULT gen_random_uuid()`
    );
  }

  for (const field of fields) {
    cols.push(emitColumn(field, entity.name));
    const check = enumCheck(field);
    if (check) checks.push(check);
  }

  if (!declaredNames.has("created_at")) {
    cols.push(
      `  ${quoteIdent("created_at")} TIMESTAMPTZ NOT NULL DEFAULT now()`
    );
  }
  if (!declaredNames.has("updated_at")) {
    cols.push(
      `  ${quoteIdent("updated_at")} TIMESTAMPTZ NOT NULL DEFAULT now()`
    );
  }
  if (softDelete && !declaredNames.has("deleted_at")) {
    cols.push(`  ${quoteIdent("deleted_at")} TIMESTAMPTZ`);
  }

  const body = [...cols, ...checks].join(",\n");
  return [
    `-- entity ${entity.name}`,
    `CREATE TABLE ${table} (`,
    body,
    `);`,
  ];
}

function emitColumn(field: FieldDecl, _entityName: string): string {
  const type = field.type;
  const isFk = type.kind === "BelongsTo";
  const colName = quoteIdent(
    isFk ? fkColumnName(field.name) : toSnakeField(field.name)
  );
  let sql = `  ${colName} ${sqlType(type)}`;

  const required = field.modifiers.some((m) => m.kind === "required");
  const optional =
    field.modifiers.some((m) => m.kind === "optional") ||
    (type.kind === "BelongsTo" && type.optional);
  const unique = field.modifiers.some((m) => m.kind === "unique");
  const def = field.modifiers.find((m) => m.kind === "default");

  if (unique) sql += " UNIQUE";
  if (required && !optional) sql += " NOT NULL";
  if (def && def.kind === "default") {
    sql += ` DEFAULT ${formatDefault(def.value)}`;
  }

  if (type.kind === "BelongsTo") {
    sql += ` REFERENCES ${quoteIdent(tableName(type.entity))} (${quoteIdent("id")})`;
  }

  if (field.name === "id" && type.kind === "Primitive" && type.name === "uuid") {
    if (!sql.includes("PRIMARY KEY")) {
      sql += " PRIMARY KEY";
    }
    if (!sql.includes("DEFAULT")) {
      sql += " DEFAULT gen_random_uuid()";
    }
  }

  return sql;
}

function toSnakeField(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
}

function enumCheck(field: FieldDecl): string | null {
  if (field.type.kind !== "Enum") return null;
  const col = quoteIdent(toSnakeField(field.name));
  const list = field.type.variants
    .map((v) => `'${v.replace(/'/g, "''")}'`)
    .join(", ");
  return `  CONSTRAINT ${quoteIdent(`${toSnakeField(field.name)}_check`)} CHECK (${col} IN (${list}))`;
}

/** Exported for tests. */
export function sqlTypeFor(type: TypeExpr): string {
  return sqlType(type);
}
