/** Generated by @aiparlance/workers from examples/ops-reference.aip — do not edit by hand. */
/** App: OpsDemo @0.1 */

/** Declared queue names. */
export const queues = {
  SendEmail: "SendEmail",
} as const;

export type QueueName = (typeof queues)[keyof typeof queues];

/** Declared job names. */
export const jobs = {
  SendWelcomeEmail: "SendWelcomeEmail",
  SendReminder: "SendReminder",
} as const;

export type JobName = (typeof jobs)[keyof typeof jobs];

/**
 * Job stub: SendWelcomeEmail (retries: 3, timeout: 1m).
 * Dispatched from workflow(s): LeadIntake.
 * Wire your queue worker to call this handler.
 */
export async function handleSendWelcomeEmail(_payload: unknown): Promise<void> {
  throw new Error("job SendWelcomeEmail not implemented");
}

/**
 * Job stub: SendReminder (retries: 2, timeout: 30m).
 * Dispatched from workflow(s): LeadIntake.
 * Wire your queue worker to call this handler.
 */
export async function handleSendReminder(_payload: unknown): Promise<void> {
  throw new Error("job SendReminder not implemented");
}

/** Workflow → job dispatch edges (for wiring / docs). */
export const dispatches = [
  { workflow: "LeadIntake", job: "SendWelcomeEmail" },
  { workflow: "LeadIntake", job: "SendReminder", after: "15m" },
] as const;
