<?php

/** Generated by @aiparlance/php from examples/minimal.aip — do not edit by hand. */

declare(strict_types=1);

class User
{
    public string $id;
    public string $name;
    public string $email;
    public string $created_at;
    public string $updated_at;
}

class UserCreate
{
    public string $name;
    public string $email;
}

class UserUpdate
{
    public ?string $name;
    public ?string $email;
}
