import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  PrimitiveType,
  TypeExpr,
  ValidationBlock,
} from "@aiparlance/parser";
import { fkColumnName, toSnakeCase } from "@aiparlance/sql";

export class EmitPythonError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitPythonError";
  }
}

type Mode = "full" | "create" | "update";

type FieldOut = {
  name: string;
  pyType: string;
  optional: boolean;
};

/**
 * Emit Python dataclasses (stdlib typing only) from a Core AST.
 */
export function emitPython(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitPythonError("no entity blocks to emit");
  }

  const validations = doc.blocks.filter(
    (b): b is ValidationBlock => b.kind === "Validation"
  );

  const needsOptional = entities.some((e) => {
    const create = fieldsFor(e, "create", validations);
    const update = fieldsFor(e, "update", validations);
    const full = fieldsFor(e, "full", validations);
    return [...create, ...update, ...full].some((f) => f.optional);
  });

  const needsLiteral = entities.some((e) =>
    e.body.some((b) => b.kind === "Field" && b.type.kind === "Enum")
  );
  const needsAny = entities.some((e) =>
    e.body.some(
      (b) =>
        b.kind === "Field" &&
        b.type.kind === "Primitive" &&
        b.type.name === "json"
    )
  );

  const typingImports: string[] = [];
  if (needsAny) typingImports.push("Any");
  if (needsLiteral) typingImports.push("Literal");
  if (needsOptional) typingImports.push("Optional");

  const lines: string[] = [
    `# Generated by @aiparlance/python from ${doc.fileName} — do not edit by hand.`,
    `from __future__ import annotations`,
    ``,
    `from dataclasses import dataclass`,
  ];

  if (typingImports.length > 0) {
    lines.push(`from typing import ${typingImports.join(", ")}`);
  }
  lines.push("");

  for (const entity of entities) {
    const full = fieldsFor(entity, "full", validations);
    const create = fieldsFor(entity, "create", validations);
    const update = fieldsFor(entity, "update", validations);

    lines.push(emitDataclass(entity.name, full));
    lines.push("");
    lines.push(emitDataclass(`${entity.name}Create`, create));
    lines.push("");
    lines.push(emitDataclass(`${entity.name}Update`, update));
    lines.push("");
  }

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function emitDataclass(name: string, fields: FieldOut[]): string {
  const body =
    fields.length === 0
      ? "    pass"
      : fields
          .map((f) => {
            if (f.optional) {
              return `    ${f.name}: Optional[${f.pyType}] = None`;
            }
            return `    ${f.name}: ${f.pyType}`;
          })
          .join("\n");
  return `@dataclass\nclass ${name}:\n${body}`;
}

function fieldsFor(
  entity: EntityBlock,
  mode: Mode,
  validations: ValidationBlock[]
): FieldOut[] {
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declared = new Set(fields.map((f) => f.name));
  const out: FieldOut[] = [];

  if (mode === "full" && !declared.has("id")) {
    out.push({ name: "id", pyType: "str", optional: false });
  }

  for (const field of fields) {
    const name = propertyName(field);
    const pyType = mapType(field.type);
    const isOptional =
      field.modifiers.some((m) => m.kind === "optional") ||
      (field.type.kind === "BelongsTo" && field.type.optional);
    const isRequired =
      (field.modifiers.some((m) => m.kind === "required") ||
        validationHas(validations, entity.name, field.name, "required")) &&
      !isOptional;

    if (mode === "update") {
      out.push({ name, pyType, optional: true });
      continue;
    }

    if (mode === "full" && isOptional) {
      out.push({ name, pyType, optional: true });
      continue;
    }

    if (mode === "create") {
      out.push({ name, pyType, optional: !isRequired });
      continue;
    }

    out.push({ name, pyType, optional: false });
  }

  if (mode === "full") {
    if (!declared.has("created_at")) {
      out.push({ name: "created_at", pyType: "str", optional: false });
    }
    if (!declared.has("updated_at")) {
      out.push({ name: "updated_at", pyType: "str", optional: false });
    }
    if (softDelete && !declared.has("deleted_at")) {
      out.push({ name: "deleted_at", pyType: "str", optional: true });
    }
  }

  // dataclass rule: non-default fields before defaulted ones
  const required = out.filter((f) => !f.optional);
  const optional = out.filter((f) => f.optional);
  return [...required, ...optional];
}

function propertyName(field: FieldDecl): string {
  if (field.type.kind === "BelongsTo") return fkColumnName(field.name);
  return toSnakeCase(field.name);
}

function mapType(type: TypeExpr): string {
  switch (type.kind) {
    case "Primitive":
      return mapPrimitive(type.name);
    case "Enum": {
      if (type.variants.length === 0) return "str";
      return `Literal[${type.variants.map((v) => JSON.stringify(v)).join(", ")}]`;
    }
    case "BelongsTo":
    case "EntityRef":
      return "str";
  }
}

function mapPrimitive(name: PrimitiveType): string {
  switch (name) {
    case "string":
    case "text":
    case "phone":
    case "email":
    case "uuid":
    case "datetime":
    case "date":
      return "str";
    case "int":
      return "int";
    case "float":
      return "float";
    case "bool":
      return "bool";
    case "json":
      return "dict[str, Any]";
  }
}

function validationHas(
  validations: ValidationBlock[],
  entity: string,
  field: string,
  mod: "required" | "unique"
): boolean {
  for (const block of validations) {
    if (block.entity !== entity) continue;
    for (const rule of block.rules) {
      if (rule.field === field && rule.modifiers.includes(mod)) return true;
    }
  }
  return false;
}
