import type {
  AipDocument,
  DefaultValue,
  EntityBlock,
  Expr,
  FieldDecl,
  IndexBlock,
  PrimitiveType,
  SeedBlock,
  TypeExpr,
} from "@aiparlance/parser";
import { fkColumnName, tableName, toSnakeCase } from "@aiparlance/sql";

export class EmitMysqlError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitMysqlError";
  }
}

/**
 * Emit MySQL DDL from a Core AST (secondary dialect after PostgreSQL).
 * Assumes the document already passed semantic validation.
 */
export function emitMysql(doc: AipDocument): string {
  const db = doc.app.members.find((m) => m.kind === "database");
  if (!db || db.kind !== "database") {
    throw new EmitMysqlError("app.database is required to emit MySQL");
  }
  if (db.engine === "postgres") {
    throw new EmitMysqlError(
      "app.database is postgres — use `aip emit sql` for PostgreSQL, or set database mysql"
    );
  }
  if (db.engine !== "mysql") {
    throw new EmitMysqlError(
      `MySQL emitter supports mysql only (got '${db.engine}')`
    );
  }

  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitMysqlError("no entity blocks to emit");
  }

  const ordered = orderEntities(entities);
  const lines: string[] = [
    `-- Generated by @aiparlance/mysql (MySQL)`,
    `-- App: ${doc.app.name}${doc.app.version ? ` @${doc.app.version}` : ""}`,
    `-- Source: ${doc.fileName}`,
    ``,
  ];

  for (const entity of ordered) {
    lines.push(...emitCreateTable(entity));
    lines.push(``);
  }

  const indexes = doc.blocks.filter((b): b is IndexBlock => b.kind === "Index");
  for (const idx of indexes) {
    lines.push(...emitIndex(idx));
    lines.push(``);
  }

  const seeds = doc.blocks.filter((b): b is SeedBlock => b.kind === "Seed");
  for (const seed of seeds) {
    lines.push(...emitSeed(seed));
    lines.push(``);
  }

  return lines.join("\n").replace(/\n+$/, "\n");
}

function orderEntities(entities: EntityBlock[]): EntityBlock[] {
  const byName = new Map(entities.map((e) => [e.name, e]));
  const deps = new Map<string, Set<string>>();

  for (const e of entities) {
    const needs = new Set<string>();
    for (const item of e.body) {
      if (item.kind !== "Field") continue;
      if (item.type.kind === "BelongsTo" && byName.has(item.type.entity)) {
        if (item.type.entity !== e.name) needs.add(item.type.entity);
      }
    }
    deps.set(e.name, needs);
  }

  const result: EntityBlock[] = [];
  const visiting = new Set<string>();
  const done = new Set<string>();

  function visit(name: string): void {
    if (done.has(name)) return;
    if (visiting.has(name)) {
      throw new EmitMysqlError(
        `cyclic belongs_to involving entity '${name}'`
      );
    }
    visiting.add(name);
    for (const dep of deps.get(name) ?? []) visit(dep);
    visiting.delete(name);
    done.add(name);
    const entity = byName.get(name);
    if (entity) result.push(entity);
  }

  for (const e of entities) visit(e.name);
  return result;
}

function emitCreateTable(entity: EntityBlock): string[] {
  const table = quoteIdent(tableName(entity.name));
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declaredNames = new Set(fields.map((f) => f.name));

  const cols: string[] = [];
  const checks: string[] = [];

  if (!declaredNames.has("id")) {
    cols.push(
      `  ${quoteIdent("id")} CHAR(36) PRIMARY KEY DEFAULT (UUID())`
    );
  }

  for (const field of fields) {
    cols.push(emitColumn(field));
    const check = enumCheck(field);
    if (check) checks.push(check);
  }

  if (!declaredNames.has("created_at")) {
    cols.push(
      `  ${quoteIdent("created_at")} DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`
    );
  }
  if (!declaredNames.has("updated_at")) {
    cols.push(
      `  ${quoteIdent("updated_at")} DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`
    );
  }
  if (softDelete && !declaredNames.has("deleted_at")) {
    cols.push(`  ${quoteIdent("deleted_at")} DATETIME(6)`);
  }

  const body = [...cols, ...checks].join(",\n");
  return [
    `-- entity ${entity.name}`,
    `CREATE TABLE ${table} (`,
    body,
    `);`,
  ];
}

function emitIndex(idx: IndexBlock): string[] {
  const table = quoteIdent(tableName(idx.entity));
  const cols = idx.fields.map((f) => quoteIdent(toSnakeCase(f))).join(", ");
  const name = quoteIdent(
    `idx_${tableName(idx.entity)}_${idx.fields.map((f) => toSnakeCase(f)).join("_")}`
  );
  return [
    `-- index ${idx.entity}`,
    `CREATE INDEX ${name} ON ${table} (${cols});`,
  ];
}

function emitSeed(seed: SeedBlock): string[] {
  const table = quoteIdent(tableName(seed.entity));
  const cols = seed.assigns
    .map((a) => quoteIdent(toSnakeCase(a.name)))
    .join(", ");
  const vals = seed.assigns.map((a) => exprToSql(a.value)).join(", ");
  return [
    `-- seed ${seed.entity}`,
    `INSERT INTO ${table} (${cols}) VALUES (${vals});`,
  ];
}

function exprToSql(expr: Expr): string {
  switch (expr.kind) {
    case "string":
      return `'${expr.value.replace(/'/g, "''")}'`;
    case "number":
      return String(expr.value);
    case "boolean":
      return expr.value ? "TRUE" : "FALSE";
    case "duration":
      return `'${expr.value.amount}${expr.value.unit}'`;
    case "field_ref":
      return `'${expr.ref.parts.join(".").replace(/'/g, "''")}'`;
    case "call":
      return `'${expr.name}()'`;
    case "binary":
      return `(${exprToSql(expr.left)} ${expr.op} ${exprToSql(expr.right)})`;
  }
}

function emitColumn(field: FieldDecl): string {
  const type = field.type;
  const isFk = type.kind === "BelongsTo";
  const colName = quoteIdent(
    isFk ? fkColumnName(field.name) : toSnakeCase(field.name)
  );
  let sql = `  ${colName} ${mysqlType(type)}`;

  const required = field.modifiers.some((m) => m.kind === "required");
  const optional =
    field.modifiers.some((m) => m.kind === "optional") ||
    (type.kind === "BelongsTo" && type.optional);
  const unique = field.modifiers.some((m) => m.kind === "unique");
  const def = field.modifiers.find((m) => m.kind === "default");

  if (unique) sql += " UNIQUE";
  if (required && !optional) sql += " NOT NULL";
  if (def && def.kind === "default") {
    sql += ` DEFAULT ${formatDefault(def.value)}`;
  }

  if (type.kind === "BelongsTo") {
    sql += ` REFERENCES ${quoteIdent(tableName(type.entity))} (${quoteIdent("id")})`;
  }

  if (field.name === "id" && type.kind === "Primitive" && type.name === "uuid") {
    if (!sql.includes("PRIMARY KEY")) {
      sql += " PRIMARY KEY";
    }
    if (!sql.includes("DEFAULT")) {
      sql += " DEFAULT (UUID())";
    }
  }

  return sql;
}

function mysqlType(type: TypeExpr): string {
  switch (type.kind) {
    case "Primitive":
      return mapPrimitive(type.name);
    case "Enum":
      return "TEXT";
    case "BelongsTo":
    case "EntityRef":
      return "CHAR(36)";
  }
}

function mapPrimitive(name: PrimitiveType): string {
  switch (name) {
    case "string":
    case "text":
    case "email":
    case "phone":
      return "TEXT";
    case "int":
      return "INT";
    case "float":
      return "DOUBLE";
    case "bool":
      return "BOOLEAN";
    case "datetime":
      return "DATETIME(6)";
    case "date":
      return "DATE";
    case "uuid":
      return "CHAR(36)";
    case "json":
      return "JSON";
  }
}

function formatDefault(value: DefaultValue): string {
  switch (value.kind) {
    case "string":
      return `'${value.value.replace(/'/g, "''")}'`;
    case "number":
      return String(value.value);
    case "boolean":
      return value.value ? "TRUE" : "FALSE";
    case "ident":
      return `'${value.value.replace(/'/g, "''")}'`;
  }
}

function quoteIdent(ident: string): string {
  if (/^[a-z_][a-z0-9_]*$/.test(ident)) return ident;
  return `\`${ident.replace(/`/g, "``")}\``;
}

function enumCheck(field: FieldDecl): string | null {
  if (field.type.kind !== "Enum") return null;
  const col = quoteIdent(toSnakeCase(field.name));
  const list = field.type.variants
    .map((v) => `'${v.replace(/'/g, "''")}'`)
    .join(", ");
  return `  CONSTRAINT ${quoteIdent(`${toSnakeCase(field.name)}_check`)} CHECK (${col} IN (${list}))`;
}
