import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  TypeExpr,
} from "@aiparlance/parser";
import { fkColumnName, tableName, toSnakeCase } from "@aiparlance/sql";

export class EmitDocsError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitDocsError";
  }
}

/**
 * Emit a Markdown API reference from entities + crud + api prefix.
 */
export function emitDocs(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitDocsError("no entity blocks to emit");
  }

  const crudEntities = new Set(
    doc.blocks
      .filter((b) => b.kind === "Crud")
      .map((b) => (b.kind === "Crud" ? b.entity : ""))
  );

  let pathPrefix = "";
  const api = doc.blocks.find((b) => b.kind === "Api");
  if (api && api.kind === "Api") {
    const prefix = api.members.find((m) => m.kind === "prefix");
    if (prefix && prefix.kind === "prefix") {
      pathPrefix = prefix.value.replace(/\/$/, "");
    }
  }

  const version = doc.app.version ?? "0.1";
  const lines: string[] = [
    `# ${doc.app.name} API`,
    ``,
    `Generated by \`@aiparlance/docs\` from \`${doc.fileName}\`.`,
    ``,
    `| | |`,
    `|---|---|`,
    `| Version | ${version} |`,
    `| Database | ${databaseEngine(doc)} |`,
    pathPrefix ? `| API prefix | \`${pathPrefix}\` |` : `| API prefix | _(none)_ |`,
    ``,
  ];

  for (const entity of entities) {
    lines.push(`## ${entity.name}`);
    lines.push(``);
    lines.push(`### Fields`);
    lines.push(``);
    lines.push(`| Field | Type | Notes |`);
    lines.push(`|---|---|---|`);

    const softDelete = entity.body.some((m) => m.kind === "soft_delete");
    const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
    const declared = new Set(fields.map((f) => f.name));

    if (!declared.has("id")) {
      lines.push(`| \`id\` | uuid | primary key (implicit) |`);
    }

    for (const field of fields) {
      const name =
        field.type.kind === "BelongsTo"
          ? fkColumnName(field.name)
          : toSnakeCase(field.name);
      const notes = fieldNotes(field);
      lines.push(
        `| \`${name}\` | ${typeLabel(field.type)} | ${notes || "—"} |`
      );
    }

    if (!declared.has("created_at")) {
      lines.push(`| \`created_at\` | datetime | implicit timestamp |`);
    }
    if (!declared.has("updated_at")) {
      lines.push(`| \`updated_at\` | datetime | implicit timestamp |`);
    }
    if (softDelete && !declared.has("deleted_at")) {
      lines.push(`| \`deleted_at\` | datetime | soft delete |`);
    }

    lines.push(``);

    if (crudEntities.has(entity.name)) {
      const collection = `${pathPrefix}/${tableName(entity.name)}`;
      const item = `${collection}/{id}`;
      lines.push(`### Endpoints`);
      lines.push(``);
      lines.push(`| Method | Path | Description |`);
      lines.push(`|---|---|---|`);
      lines.push(`| GET | \`${collection}\` | List ${entity.name} |`);
      lines.push(`| POST | \`${collection}\` | Create ${entity.name} |`);
      lines.push(`| GET | \`${item}\` | Get ${entity.name} |`);
      lines.push(`| PUT | \`${item}\` | Update ${entity.name} |`);
      lines.push(`| DELETE | \`${item}\` | Delete ${entity.name} |`);
      lines.push(``);
    } else {
      lines.push(`_No \`crud\` declaration — endpoints omitted._`);
      lines.push(``);
    }
  }

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function databaseEngine(doc: AipDocument): string {
  const db = doc.app.members.find((m) => m.kind === "database");
  if (db && db.kind === "database") return db.engine;
  return "unknown";
}

function typeLabel(type: TypeExpr): string {
  switch (type.kind) {
    case "Primitive":
      return type.name;
    case "Enum":
      return `enum(${type.variants.join(", ")})`;
    case "BelongsTo":
      return `belongs_to ${type.entity}${type.optional ? "?" : ""}`;
    case "EntityRef":
      return type.name;
  }
}

function fieldNotes(field: FieldDecl): string {
  const parts: string[] = [];
  for (const m of field.modifiers) {
    if (m.kind === "required") parts.push("required");
    if (m.kind === "unique") parts.push("unique");
    if (m.kind === "optional") parts.push("optional");
    if (m.kind === "default") {
      parts.push(`default(${formatDefaultNote(m.value)})`);
    }
  }
  if (field.type.kind === "BelongsTo" && field.type.optional) {
    if (!parts.includes("optional")) parts.push("optional");
  }
  return parts.join(", ");
}

function formatDefaultNote(
  value:
    | { kind: "string"; value: string }
    | { kind: "number"; value: number }
    | { kind: "boolean"; value: boolean }
    | { kind: "ident"; value: string }
): string {
  switch (value.kind) {
    case "string":
      return JSON.stringify(value.value);
    case "number":
      return String(value.value);
    case "boolean":
      return value.value ? "true" : "false";
    case "ident":
      return value.value;
  }
}
