import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  PolicyBlock,
  PredicateExpr,
  PrimitiveType,
  TypeExpr,
  ValidationBlock,
} from "@aiparlance/parser";
import { fkColumnName, tableName, toSnakeCase } from "@aiparlance/sql";

export class EmitTypeScriptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitTypeScriptError";
  }
}

type Mode = "full" | "create" | "update";

type Prop = {
  name: string;
  tsType: string;
  required: boolean;
  guard: string;
  zod: string;
};

/**
 * Emit TypeScript: interfaces, guards, Zod schemas, path helpers (with api.prefix),
 * policy helpers, and a thin in-memory CRUD HTTP app (node:http).
 *
 * Generated modules import `zod`. Runnable app needs no DB for Preview demos.
 */
export function emitTypeScript(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitTypeScriptError("no entity blocks to emit");
  }

  const crudEntities = new Set(
    doc.blocks
      .filter((b) => b.kind === "Crud")
      .map((b) => (b.kind === "Crud" ? b.entity : ""))
  );

  const validations = doc.blocks.filter(
    (b): b is ValidationBlock => b.kind === "Validation"
  );

  const policies = new Map<string, PolicyBlock>();
  for (const b of doc.blocks) {
    if (b.kind === "Policy") policies.set(b.entity, b);
  }

  const api = doc.blocks.find((b) => b.kind === "Api");
  let pathPrefix = "";
  if (api && api.kind === "Api") {
    const prefix = api.members.find((m) => m.kind === "prefix");
    if (prefix && prefix.kind === "prefix") {
      pathPrefix = prefix.value.replace(/\/$/, "");
    }
  }

  const auth = doc.app.members.find((m) => m.kind === "auth");
  const hasAuth = Boolean(auth && auth.kind === "auth");

  const parts: string[] = [
    `/** Generated by @aiparlance/typescript from ${doc.fileName} — do not edit by hand. */`,
    `import { z } from "zod";`,
    `import { createServer, type IncomingMessage, type ServerResponse } from "node:http";`,
    `import { randomUUID } from "node:crypto";`,
    `import pg from "pg";`,
    `import * as jose from "jose";`,
    "",
  ];

  for (const entity of entities) {
    parts.push(emitEntity(entity, validations));
    if (crudEntities.has(entity.name)) {
      parts.push(emitCrudPaths(entity, pathPrefix));
    }
    const policy = policies.get(entity.name);
    if (policy) {
      parts.push(emitPolicyConst(policy));
    }
  }

  const crudList = entities.filter((e) => crudEntities.has(e.name));
  if (crudList.length > 0) {
    parts.push(
      emitRuntimeApp(crudList, policies, pathPrefix, hasAuth, validations)
    );
  }

  return `${parts.join("\n").replace(/\n+$/, "")}\n`;
}

function emitEntity(
  entity: EntityBlock,
  validations: ValidationBlock[]
): string {
  const full = propsFor(entity, "full", validations);
  const create = propsFor(entity, "create", validations);
  const update = propsFor(entity, "update", validations);

  return [
    emitInterface(entity.name, full),
    "",
    emitInterface(`${entity.name}Create`, create),
    "",
    emitInterface(`${entity.name}Update`, update),
    "",
    emitGuard(`is${entity.name}`, entity.name, full),
    "",
    emitGuard(`is${entity.name}Create`, `${entity.name}Create`, create),
    "",
    emitZodSchemas(entity.name, create, update, full),
    "",
  ].join("\n");
}

function emitZodSchemas(
  name: string,
  create: Prop[],
  update: Prop[],
  full: Prop[]
): string {
  const zObj = (props: Prop[], partial: boolean) => {
    const fields = props
      .map((p) => {
        const base = p.required && !partial ? p.zod : `${p.zod}.optional()`;
        return `  ${p.name}: ${partial ? `${p.zod}.optional()` : base},`;
      })
      .join("\n");
    return `z.object({\n${fields}\n})`;
  };

  return [
    `export const ${name}CreateSchema = ${zObj(create, false)};`,
    `export const ${name}UpdateSchema = ${zObj(update, true)};`,
    `export const ${name}Schema = ${zObj(full, false)};`,
  ].join("\n");
}

function emitInterface(name: string, props: Prop[]): string {
  const body = props
    .map((p) => {
      const opt = p.required ? "" : "?";
      return `  ${p.name}${opt}: ${p.tsType};`;
    })
    .join("\n");
  return `export interface ${name} {\n${body}\n}`;
}

function emitGuard(fn: string, typeName: string, props: Prop[]): string {
  const checks = props.map((p) => {
    if (p.required) {
      return `    ${p.guard}`;
    }
    return `    (v.${p.name} === undefined || ${p.guard})`;
  });
  return [
    `export function ${fn}(value: unknown): value is ${typeName} {`,
    `  if (typeof value !== "object" || value === null) return false;`,
    `  const v = value as Record<string, unknown>;`,
    `  return (`,
    checks.join(" &&\n"),
    `  );`,
    `}`,
  ].join("\n");
}

function emitCrudPaths(entity: EntityBlock, pathPrefix: string): string {
  const collection = `${pathPrefix}/${tableName(entity.name)}`;
  const constName = `${lcFirst(entity.name)}Paths`;
  return [
    `/** Thin typed CRUD path helpers for ${entity.name}. */`,
    `export const ${constName} = {`,
    `  collection: "${collection}",`,
    `  item: (id: string) => \`${collection}/\${id}\` as const,`,
    `} as const;`,
    "",
  ].join("\n");
}

function emitPolicyConst(policy: PolicyBlock): string {
  const entries = policy.rules
    .map((r) => `  ${r.action}: ${JSON.stringify(describePredicate(r.predicate))} as const,`)
    .join("\n");
  return [
    `/** Policy predicates for ${policy.entity} (from .aip). */`,
    `export const ${lcFirst(policy.entity)}Policy = {`,
    entries,
    `} as const;`,
    "",
  ].join("\n");
}

function describePredicate(pred: PredicateExpr): string {
  switch (pred.kind) {
    case "public":
      return "public";
    case "authenticated":
      return "authenticated";
    case "role":
      return `role(${pred.name})`;
    case "permission":
      return `permission(${pred.name})`;
    case "owner":
      return `owner(${pred.field.parts.join(".")})`;
    case "owner_or_manager":
      return `owner_or_manager(${pred.field.parts.join(".")})`;
  }
}

function emitRuntimeApp(
  crudEntities: EntityBlock[],
  policies: Map<string, PolicyBlock>,
  pathPrefix: string,
  hasAuth: boolean,
  validations: ValidationBlock[]
): string {
  const resourceEntries = crudEntities
    .map((e) => {
      const soft = e.body.some((m) => m.kind === "soft_delete");
      const policy = policies.get(e.name);
      const rules = policy
        ? Object.fromEntries(
            policy.rules.map((r) => [r.action, describePredicate(r.predicate)])
          )
        : {};
      const ownerField = ownerFieldFor(policy);
      return `  ${JSON.stringify(tableName(e.name))}: {
    createSchema: ${e.name}CreateSchema,
    updateSchema: ${e.name}UpdateSchema,
    softDelete: ${soft ? "true" : "false"},
    policy: ${JSON.stringify(rules)} as Record<string, string>,
    ownerField: ${ownerField ? JSON.stringify(ownerField) : "null"},
  }`;
    })
    .join(",\n");

  void validations;

  return `
/** Request actor after auth. */
export type CrudActor = {
  authenticated: boolean;
  id?: string;
  role?: string;
};

export type CrudAppOptions = {
  /** Force store. Default: \`pg\` when DATABASE_URL is set, else \`memory\`. */
  store?: "memory" | "pg";
  /** HS256 secret. Default: process.env.AIP_JWT_SECRET. */
  jwtSecret?: string;
  databaseUrl?: string;
};

const __aipResources = {
${resourceEntries}
} as const;

type __AipResourceName = keyof typeof __aipResources;

const __aipMem = new Map<__AipResourceName, Map<string, Record<string, unknown>>>();
for (const name of Object.keys(__aipResources) as __AipResourceName[]) {
  __aipMem.set(name, new Map());
}

let __aipPool: pg.Pool | null = null;

function __aipUsePg(opts?: CrudAppOptions): boolean {
  const mode = opts?.store ?? (process.env.DATABASE_URL ? "pg" : "memory");
  return mode === "pg";
}

function __aipPoolOrThrow(opts?: CrudAppOptions): pg.Pool {
  if (__aipPool) return __aipPool;
  const url = opts?.databaseUrl ?? process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL is required for store: pg");
  }
  __aipPool = new pg.Pool({ connectionString: url });
  return __aipPool;
}

async function __aipActor(req: IncomingMessage, opts?: CrudAppOptions): Promise<CrudActor> {
  const header = req.headers.authorization;
  if (!header || !String(header).toLowerCase().startsWith("bearer ")) {
    return { authenticated: false };
  }
  const token = String(header).slice(7).trim();
  const secret = opts?.jwtSecret ?? process.env.AIP_JWT_SECRET;
  if (secret) {
    try {
      const { payload } = await jose.jwtVerify(
        token,
        new TextEncoder().encode(secret)
      );
      const id =
        typeof payload.sub === "string"
          ? payload.sub
          : typeof payload.id === "string"
            ? payload.id
            : undefined;
      const role =
        typeof payload.role === "string" ? payload.role : undefined;
      return { authenticated: true, id, role };
    } catch {
      return { authenticated: false };
    }
  }
  // Preview fallback without AIP_JWT_SECRET: any Bearer + optional x-aip-* headers.
  const idHeader = req.headers["x-aip-user-id"];
  const roleHeader = req.headers["x-aip-role"];
  return {
    authenticated: true,
    id: typeof idHeader === "string" ? idHeader : undefined,
    role: typeof roleHeader === "string" ? roleHeader : undefined,
  };
}

function __aipAllow(policy: string | undefined, actor: CrudActor, row?: Record<string, unknown>, ownerField?: string | null): boolean {
  if (!policy || policy === "public") return true;
  if (policy === "authenticated") return actor.authenticated;
  if (policy.startsWith("role(")) {
    const role = policy.slice(5, -1);
    return actor.authenticated && actor.role === role;
  }
  if (policy.startsWith("permission(")) {
    return actor.authenticated;
  }
  if (policy.startsWith("owner") && ownerField && row) {
    if (!actor.authenticated || !actor.id) return false;
    return row[ownerField] === actor.id;
  }
  return ${hasAuth ? "actor.authenticated" : "true"};
}

function __aipReadBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
    req.on("end", () => {
      const raw = Buffer.concat(chunks).toString("utf8");
      if (!raw) return resolve({});
      try {
        resolve(JSON.parse(raw));
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });
}

function __aipJson(res: ServerResponse, status: number, body: unknown): void {
  const data = body === undefined ? "" : JSON.stringify(body);
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "access-control-allow-origin": "*",
    "access-control-allow-headers": "authorization, content-type, x-aip-user-id, x-aip-role",
    "access-control-allow-methods": "GET,POST,PUT,DELETE,OPTIONS",
  });
  res.end(data);
}

async function __aipList(resource: __AipResourceName, softDelete: boolean, opts?: CrudAppOptions): Promise<Record<string, unknown>[]> {
  if (!__aipUsePg(opts)) {
    return [...__aipMem.get(resource)!.values()].filter((row) =>
      softDelete ? row.deleted_at == null : true
    );
  }
  const pool = __aipPoolOrThrow(opts);
  const where = softDelete ? " WHERE deleted_at IS NULL" : "";
  const { rows } = await pool.query(\`SELECT * FROM \${resource}\${where}\`);
  return rows as Record<string, unknown>[];
}

async function __aipGet(resource: __AipResourceName, id: string, softDelete: boolean, opts?: CrudAppOptions): Promise<Record<string, unknown> | null> {
  if (!__aipUsePg(opts)) {
    const row = __aipMem.get(resource)!.get(id);
    if (!row) return null;
    if (softDelete && row.deleted_at != null) return null;
    return row;
  }
  const pool = __aipPoolOrThrow(opts);
  const where = softDelete
    ? "WHERE id = $1 AND deleted_at IS NULL"
    : "WHERE id = $1";
  const { rows } = await pool.query(\`SELECT * FROM \${resource} \${where}\`, [id]);
  return (rows[0] as Record<string, unknown>) ?? null;
}

async function __aipInsert(resource: __AipResourceName, row: Record<string, unknown>, opts?: CrudAppOptions): Promise<Record<string, unknown>> {
  if (!__aipUsePg(opts)) {
    __aipMem.get(resource)!.set(String(row.id), row);
    return row;
  }
  const pool = __aipPoolOrThrow(opts);
  const cols = Object.keys(row);
  const vals = cols.map((c) => row[c]);
  const placeholders = cols.map((_, i) => \`$\${i + 1}\`);
  const { rows } = await pool.query(
    \`INSERT INTO \${resource} (\${cols.join(", ")}) VALUES (\${placeholders.join(", ")}) RETURNING *\`,
    vals
  );
  return rows[0] as Record<string, unknown>;
}

async function __aipUpdate(resource: __AipResourceName, id: string, patch: Record<string, unknown>, opts?: CrudAppOptions): Promise<Record<string, unknown> | null> {
  if (!__aipUsePg(opts)) {
    const store = __aipMem.get(resource)!;
    const existing = store.get(id);
    if (!existing) return null;
    const row = { ...existing, ...patch };
    store.set(id, row);
    return row;
  }
  const pool = __aipPoolOrThrow(opts);
  const cols = Object.keys(patch);
  if (cols.length === 0) return __aipGet(resource, id, false, opts);
  const sets = cols.map((c, i) => \`\${c} = $\${i + 1}\`);
  const vals = [...cols.map((c) => patch[c]), id];
  const { rows } = await pool.query(
    \`UPDATE \${resource} SET \${sets.join(", ")} WHERE id = $\${cols.length + 1} RETURNING *\`,
    vals
  );
  return (rows[0] as Record<string, unknown>) ?? null;
}

async function __aipDelete(resource: __AipResourceName, id: string, softDelete: boolean, opts?: CrudAppOptions): Promise<boolean> {
  if (!__aipUsePg(opts)) {
    const store = __aipMem.get(resource)!;
    const existing = store.get(id);
    if (!existing) return false;
    if (softDelete) {
      store.set(id, {
        ...existing,
        deleted_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      });
    } else {
      store.delete(id);
    }
    return true;
  }
  const pool = __aipPoolOrThrow(opts);
  if (softDelete) {
    const { rowCount } = await pool.query(
      \`UPDATE \${resource} SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL\`,
      [id]
    );
    return (rowCount ?? 0) > 0;
  }
  const { rowCount } = await pool.query(\`DELETE FROM \${resource} WHERE id = $1\`, [id]);
  return (rowCount ?? 0) > 0;
}

/**
 * Thin runnable CRUD app.
 * - Store: Postgres when \`DATABASE_URL\` (or \`opts.store: "pg"\`), else in-memory.
 * - Auth: JWT HS256 when \`AIP_JWT_SECRET\` (claims \`sub\`/\`id\`, \`role\`); else Bearer + x-aip-* Preview headers.
 * - Prefix: ${pathPrefix || "/"}.
 */
export function createCrudApp(opts?: CrudAppOptions): ReturnType<typeof createServer> {
  const prefix: string = ${JSON.stringify(pathPrefix)};
  if (__aipUsePg(opts)) {
    __aipPoolOrThrow(opts);
  }
  return createServer(async (req, res) => {
    try {
      if (req.method === "OPTIONS") {
        __aipJson(res, 204, undefined);
        return;
      }
      const url = new URL(req.url ?? "/", "http://localhost");
      let pathname = url.pathname;
      if (prefix.length > 0 && pathname.startsWith(prefix)) {
        pathname = pathname.slice(prefix.length) || "/";
      }
      const parts = pathname.split("/").filter(Boolean);
      if (parts.length === 0 || parts.length > 2) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }
      const resource = parts[0] as __AipResourceName;
      const meta = __aipResources[resource];
      if (!meta) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }
      const actor = await __aipActor(req, opts);
      const id = parts[1];
      const method = req.method ?? "GET";

      if (method === "GET" && !id) {
        if (!__aipAllow(meta.policy.read ?? meta.policy.list, actor)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        __aipJson(res, 200, await __aipList(resource, meta.softDelete, opts));
        return;
      }

      if (method === "POST" && !id) {
        if (!__aipAllow(meta.policy.create, actor)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        const body = await __aipReadBody(req);
        const parsed = meta.createSchema.safeParse(body);
        if (!parsed.success) {
          __aipJson(res, 400, { error: "validation_failed", details: parsed.error.flatten() });
          return;
        }
        const now = new Date().toISOString();
        const row: Record<string, unknown> = {
          id: randomUUID(),
          ...parsed.data,
          created_at: now,
          updated_at: now,
          ...(meta.softDelete ? { deleted_at: null } : {}),
        };
        __aipJson(res, 201, await __aipInsert(resource, row, opts));
        return;
      }

      if (!id) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }

      const existing = await __aipGet(resource, id, meta.softDelete && method === "GET", opts);
      if (!existing) {
        __aipJson(res, 404, { error: "not_found" });
        return;
      }

      if (method === "GET") {
        if (!__aipAllow(meta.policy.read, actor, existing, meta.ownerField)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        __aipJson(res, 200, existing);
        return;
      }

      if (method === "PUT") {
        if (!__aipAllow(meta.policy.update, actor, existing, meta.ownerField)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        const body = await __aipReadBody(req);
        const parsed = meta.updateSchema.safeParse(body);
        if (!parsed.success) {
          __aipJson(res, 400, { error: "validation_failed", details: parsed.error.flatten() });
          return;
        }
        const row = await __aipUpdate(
          resource,
          id,
          { ...parsed.data, updated_at: new Date().toISOString() },
          opts
        );
        __aipJson(res, 200, row);
        return;
      }

      if (method === "DELETE") {
        if (!__aipAllow(meta.policy.delete, actor, existing, meta.ownerField)) {
          __aipJson(res, actor.authenticated ? 403 : 401, { error: "forbidden" });
          return;
        }
        const ok = await __aipDelete(resource, id, meta.softDelete, opts);
        if (!ok) {
          __aipJson(res, 404, { error: "not_found" });
          return;
        }
        res.writeHead(204, { "access-control-allow-origin": "*" });
        res.end();
        return;
      }

      __aipJson(res, 405, { error: "method_not_allowed" });
    } catch (err) {
      const message = err instanceof Error ? err.message : "bad_request";
      __aipJson(res, 400, { error: "bad_request", message });
    }
  });
}

/** Sign a Preview JWT (HS256). Requires AIP_JWT_SECRET or \`secret\`. */
export async function signCrudToken(
  claims: { sub: string; role?: string },
  secret = process.env.AIP_JWT_SECRET
): Promise<string> {
  if (!secret) throw new Error("AIP_JWT_SECRET is required to sign tokens");
  return new jose.SignJWT({ role: claims.role })
    .setProtectedHeader({ alg: "HS256" })
    .setSubject(claims.sub)
    .setIssuedAt()
    .setExpirationTime("12h")
    .sign(new TextEncoder().encode(secret));
}

/** Listen helper — \`PORT\` env or 3000. */
export function listenCrudApp(
  port = Number(process.env.PORT ?? 3000),
  opts?: CrudAppOptions
): void {
  const server = createCrudApp(opts);
  server.listen(port, () => {
    const mode = __aipUsePg(opts) ? "pg" : "memory";
    console.log(\`AI Parlance CRUD (\${mode}) on http://127.0.0.1:\${port}${pathPrefix}\`);
  });
}
`.trimStart();
}

function ownerFieldFor(policy: PolicyBlock | undefined): string | null {
  if (!policy) return null;
  for (const r of policy.rules) {
    const p = r.predicate;
    if (p.kind === "owner" || p.kind === "owner_or_manager") {
      const parts = p.field.parts;
      const field = parts.length > 1 ? parts[parts.length - 1]! : parts[0]!;
      return fkColumnName(field);
    }
  }
  return null;
}

function propsFor(
  entity: EntityBlock,
  mode: Mode,
  validations: ValidationBlock[]
): Prop[] {
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declared = new Set(fields.map((f) => f.name));
  const props: Prop[] = [];

  if (mode === "full" && !declared.has("id")) {
    props.push(stringProp("id", true, "uuid"));
  }

  for (const field of fields) {
    const name = propertyName(field);
    const mapped = mapType(field.type);
    const isOptional =
      field.modifiers.some((m) => m.kind === "optional") ||
      (field.type.kind === "BelongsTo" && field.type.optional);
    const isRequired =
      (field.modifiers.some((m) => m.kind === "required") ||
        validationHas(validations, entity.name, field.name, "required")) &&
      !isOptional;

    if (mode === "update") {
      props.push({
        name,
        tsType: mapped.tsType,
        required: false,
        guard: mapped.guard(name),
        zod: mapped.zod,
      });
      continue;
    }

    if (mode === "full" && isOptional) {
      props.push({
        name,
        tsType: `${mapped.tsType} | null`,
        required: true,
        guard: `(v.${name} === null || ${mapped.guard(name)})`,
        zod: `${mapped.zod}.nullable()`,
      });
      continue;
    }

    props.push({
      name,
      tsType: mapped.tsType,
      required: mode === "create" || mode === "full" ? isRequired : false,
      guard: mapped.guard(name),
      zod: mapped.zod,
    });
  }

  if (mode === "full") {
    if (!declared.has("created_at")) {
      props.push(stringProp("created_at", true, "datetime"));
    }
    if (!declared.has("updated_at")) {
      props.push(stringProp("updated_at", true, "datetime"));
    }
    if (softDelete && !declared.has("deleted_at")) {
      props.push({
        name: "deleted_at",
        tsType: "string | null",
        required: true,
        guard: `(v.deleted_at === null || typeof v.deleted_at === "string")`,
        zod: "z.string().nullable()",
      });
    }
  }

  return props;
}

function stringProp(
  name: string,
  required: boolean,
  kind: "uuid" | "datetime"
): Prop {
  const zod =
    kind === "uuid" ? "z.string().uuid()" : "z.string().datetime({ offset: true }).or(z.string())";
  return {
    name,
    tsType: "string",
    required,
    guard: `typeof v.${name} === "string"`,
    zod,
  };
}

function propertyName(field: FieldDecl): string {
  if (field.type.kind === "BelongsTo") return fkColumnName(field.name);
  return toSnakeCase(field.name);
}

function mapType(type: TypeExpr): {
  tsType: string;
  guard: (name: string) => string;
  zod: string;
} {
  switch (type.kind) {
    case "Primitive":
      return mapPrimitive(type.name);
    case "Enum": {
      const union = type.variants.map((v) => JSON.stringify(v)).join(" | ");
      const list = type.variants.map((v) => JSON.stringify(v)).join(", ");
      return {
        tsType: union || "string",
        guard: (name) =>
          `typeof v.${name} === "string" && ([${list}] as readonly string[]).includes(v.${name})`,
        zod: `z.enum([${list}])`,
      };
    }
    case "BelongsTo":
    case "EntityRef":
      return {
        tsType: "string",
        guard: (name) => `typeof v.${name} === "string"`,
        zod: "z.string().uuid()",
      };
  }
}

function mapPrimitive(name: PrimitiveType): {
  tsType: string;
  guard: (prop: string) => string;
  zod: string;
} {
  switch (name) {
    case "string":
    case "text":
    case "phone":
      return {
        tsType: "string",
        guard: (prop) => `typeof v.${prop} === "string"`,
        zod: "z.string()",
      };
    case "email":
      return {
        tsType: "string",
        guard: (prop) => `typeof v.${prop} === "string"`,
        zod: "z.string().email()",
      };
    case "datetime":
      return {
        tsType: "string",
        guard: (prop) => `typeof v.${prop} === "string"`,
        zod: "z.string()",
      };
    case "date":
      return {
        tsType: "string",
        guard: (prop) => `typeof v.${prop} === "string"`,
        zod: "z.string()",
      };
    case "uuid":
      return {
        tsType: "string",
        guard: (prop) => `typeof v.${prop} === "string"`,
        zod: "z.string().uuid()",
      };
    case "int":
      return {
        tsType: "number",
        guard: (prop) => `typeof v.${prop} === "number"`,
        zod: "z.number().int()",
      };
    case "float":
      return {
        tsType: "number",
        guard: (prop) => `typeof v.${prop} === "number"`,
        zod: "z.number()",
      };
    case "bool":
      return {
        tsType: "boolean",
        guard: (prop) => `typeof v.${prop} === "boolean"`,
        zod: "z.boolean()",
      };
    case "json":
      return {
        tsType: "Record<string, unknown>",
        guard: (prop) =>
          `typeof v.${prop} === "object" && v.${prop} !== null && !Array.isArray(v.${prop})`,
        zod: "z.record(z.string(), z.unknown())",
      };
  }
}

function validationHas(
  validations: ValidationBlock[],
  entity: string,
  field: string,
  mod: "required" | "unique"
): boolean {
  for (const block of validations) {
    if (block.entity !== entity) continue;
    for (const rule of block.rules) {
      if (rule.field === field && rule.modifiers.includes(mod)) return true;
    }
  }
  return false;
}

function lcFirst(name: string): string {
  if (!name) return name;
  return name[0]!.toLowerCase() + name.slice(1);
}
