import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  PrimitiveType,
  TypeExpr,
  ValidationBlock,
} from "@aiparlance/parser";
import { fkColumnName, tableName, toSnakeCase } from "@aiparlance/sql";

export class EmitTypeScriptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitTypeScriptError";
  }
}

type Mode = "full" | "create" | "update";

type Prop = {
  name: string;
  tsType: string;
  /** Property required on the object (not `?`). */
  required: boolean;
  /** Runtime check expression given `v.name` (Record access). */
  guard: string;
};

/**
 * Emit TypeScript interfaces + type guards from a Core AST (Phase C / M5).
 * Assumes the document already passed semantic validation.
 * Zero runtime imports — emitted modules typecheck in isolation.
 */
export function emitTypeScript(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitTypeScriptError("no entity blocks to emit");
  }

  const crudEntities = new Set(
    doc.blocks
      .filter((b) => b.kind === "Crud")
      .map((b) => (b.kind === "Crud" ? b.entity : ""))
  );

  const validations = doc.blocks.filter(
    (b): b is ValidationBlock => b.kind === "Validation"
  );

  const parts: string[] = [
    `/** Generated by @aiparlance/typescript from ${doc.fileName} — do not edit by hand. */`,
    "",
  ];

  for (const entity of entities) {
    parts.push(emitEntity(entity, validations));
    if (crudEntities.has(entity.name)) {
      parts.push(emitCrudPaths(entity));
    }
  }

  return `${parts.join("\n").replace(/\n+$/, "")}\n`;
}

function emitEntity(
  entity: EntityBlock,
  validations: ValidationBlock[]
): string {
  const full = propsFor(entity, "full", validations);
  const create = propsFor(entity, "create", validations);
  const update = propsFor(entity, "update", validations);

  const lines: string[] = [
    emitInterface(entity.name, full),
    "",
    emitInterface(`${entity.name}Create`, create),
    "",
    emitInterface(`${entity.name}Update`, update),
    "",
    emitGuard(`is${entity.name}`, entity.name, full),
    "",
    emitGuard(`is${entity.name}Create`, `${entity.name}Create`, create),
    "",
  ];
  return lines.join("\n");
}

function emitInterface(name: string, props: Prop[]): string {
  const body = props
    .map((p) => {
      const opt = p.required ? "" : "?";
      return `  ${p.name}${opt}: ${p.tsType};`;
    })
    .join("\n");
  return `export interface ${name} {\n${body}\n}`;
}

function emitGuard(fn: string, typeName: string, props: Prop[]): string {
  const checks = props.map((p) => {
    if (p.required) {
      return `    ${p.guard}`;
    }
    return `    (v.${p.name} === undefined || ${p.guard})`;
  });
  return [
    `export function ${fn}(value: unknown): value is ${typeName} {`,
    `  if (typeof value !== "object" || value === null) return false;`,
    `  const v = value as Record<string, unknown>;`,
    `  return (`,
    checks.join(" &&\n"),
    `  );`,
    `}`,
  ].join("\n");
}

function emitCrudPaths(entity: EntityBlock): string {
  const collection = `/${tableName(entity.name)}`;
  const constName = `${lcFirst(entity.name)}Paths`;
  return [
    `/** Thin typed CRUD path helpers for ${entity.name} (framework-free). */`,
    `export const ${constName} = {`,
    `  collection: "${collection}",`,
    `  item: (id: string) => \`${collection}/\${id}\` as const,`,
    `} as const;`,
    "",
  ].join("\n");
}

function propsFor(
  entity: EntityBlock,
  mode: Mode,
  validations: ValidationBlock[]
): Prop[] {
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declared = new Set(fields.map((f) => f.name));
  const props: Prop[] = [];

  if (mode === "full" && !declared.has("id")) {
    props.push(stringProp("id", true, "uuid"));
  }

  for (const field of fields) {
    const name = propertyName(field);
    const mapped = mapType(field.type);
    const isOptional =
      field.modifiers.some((m) => m.kind === "optional") ||
      (field.type.kind === "BelongsTo" && field.type.optional);
    const isRequired =
      (field.modifiers.some((m) => m.kind === "required") ||
        validationHas(validations, entity.name, field.name, "required")) &&
      !isOptional;

    if (mode === "update") {
      props.push({
        name,
        tsType: mapped.tsType,
        required: false,
        guard: mapped.guard(name),
      });
      continue;
    }

    if (mode === "full" && isOptional) {
      props.push({
        name,
        tsType: `${mapped.tsType} | null`,
        required: true,
        guard: `(v.${name} === null || ${mapped.guard(name)})`,
      });
      continue;
    }

    props.push({
      name,
      tsType: mapped.tsType,
      required: mode === "create" || mode === "full" ? isRequired : false,
      guard: mapped.guard(name),
    });
  }

  if (mode === "full") {
    if (!declared.has("created_at")) {
      props.push(stringProp("created_at", true, "datetime"));
    }
    if (!declared.has("updated_at")) {
      props.push(stringProp("updated_at", true, "datetime"));
    }
    if (softDelete && !declared.has("deleted_at")) {
      props.push({
        name: "deleted_at",
        tsType: "string | null",
        required: true,
        guard: `(v.deleted_at === null || typeof v.deleted_at === "string")`,
      });
    }
  }

  return props;
}

function stringProp(
  name: string,
  required: boolean,
  _kind: "uuid" | "datetime"
): Prop {
  return {
    name,
    tsType: "string",
    required,
    guard: `typeof v.${name} === "string"`,
  };
}

function propertyName(field: FieldDecl): string {
  if (field.type.kind === "BelongsTo") return fkColumnName(field.name);
  return toSnakeCase(field.name);
}

function mapType(type: TypeExpr): {
  tsType: string;
  guard: (name: string) => string;
} {
  switch (type.kind) {
    case "Primitive":
      return mapPrimitive(type.name);
    case "Enum": {
      const union = type.variants.map((v) => JSON.stringify(v)).join(" | ");
      const list = type.variants.map((v) => JSON.stringify(v)).join(", ");
      return {
        tsType: union || "string",
        guard: (name) =>
          `typeof v.${name} === "string" && ([${list}] as readonly string[]).includes(v.${name})`,
      };
    }
    case "BelongsTo":
    case "EntityRef":
      return {
        tsType: "string",
        guard: (name) => `typeof v.${name} === "string"`,
      };
  }
}

function mapPrimitive(name: PrimitiveType): {
  tsType: string;
  guard: (prop: string) => string;
} {
  switch (name) {
    case "string":
    case "text":
    case "phone":
    case "email":
    case "datetime":
    case "date":
    case "uuid":
      return {
        tsType: "string",
        guard: (prop) => `typeof v.${prop} === "string"`,
      };
    case "int":
    case "float":
      return {
        tsType: "number",
        guard: (prop) => `typeof v.${prop} === "number"`,
      };
    case "bool":
      return {
        tsType: "boolean",
        guard: (prop) => `typeof v.${prop} === "boolean"`,
      };
    case "json":
      return {
        tsType: "Record<string, unknown>",
        guard: (prop) =>
          `typeof v.${prop} === "object" && v.${prop} !== null && !Array.isArray(v.${prop})`,
      };
  }
}

function validationHas(
  validations: ValidationBlock[],
  entity: string,
  field: string,
  mod: "required" | "unique"
): boolean {
  for (const block of validations) {
    if (block.entity !== entity) continue;
    for (const rule of block.rules) {
      if (rule.field === field && rule.modifiers.includes(mod)) return true;
    }
  }
  return false;
}

function lcFirst(name: string): string {
  if (!name) return name;
  return name[0]!.toLowerCase() + name.slice(1);
}
