/** Generated by @aiparlance/tests from examples/minimal.aip — do not edit by hand. */
/** Vitest-style CRUD fixtures for Demo. */

export type CrudCase = {
  name: string;
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
};

export const userCrudCases: CrudCase[] = [
  { name: "list", method: "GET", path: "/users" },
  { name: "create", method: "POST", path: "/users" },
  { name: "get", method: "GET", path: "/users/{id}" },
  { name: "update", method: "PUT", path: "/users/{id}" },
  { name: "delete", method: "DELETE", path: "/users/{id}" },
];

export const crudCases = {
  user: userCrudCases,
} as const;
