# Generated by @aiparlance/python from examples/minimal.aip — do not edit by hand.
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

@dataclass
class User:
    id: str
    name: str
    email: str
    created_at: str
    updated_at: str

@dataclass
class UserCreate:
    name: str
    email: str

@dataclass
class UserUpdate:
    name: Optional[str] = None
    email: Optional[str] = None
