import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  PrimitiveType,
  TypeExpr,
  ValidationBlock,
} from "@aiparlance/parser";
import { fkColumnName, toSnakeCase } from "@aiparlance/sql";

export class EmitPhpError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitPhpError";
  }
}

type Mode = "full" | "create" | "update";

type Prop = {
  name: string;
  phpType: string;
  nullable: boolean;
};

/**
 * Emit PHP classes with typed public properties from a Core AST.
 */
export function emitPhp(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitPhpError("no entity blocks to emit");
  }

  const validations = doc.blocks.filter(
    (b): b is ValidationBlock => b.kind === "Validation"
  );

  const lines: string[] = [
    `<?php`,
    ``,
    `/** Generated by @aiparlance/php from ${doc.fileName} — do not edit by hand. */`,
    ``,
    `declare(strict_types=1);`,
    ``,
  ];

  for (const entity of entities) {
    lines.push(emitClass(entity.name, propsFor(entity, "full", validations)));
    lines.push("");
    lines.push(
      emitClass(`${entity.name}Create`, propsFor(entity, "create", validations))
    );
    lines.push("");
    lines.push(
      emitClass(`${entity.name}Update`, propsFor(entity, "update", validations))
    );
    lines.push("");
  }

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function emitClass(name: string, props: Prop[]): string {
  const body =
    props.length === 0
      ? ""
      : props
          .map((p) => {
            const type = p.nullable ? `?${p.phpType}` : p.phpType;
            return `    public ${type} $${p.name};`;
          })
          .join("\n");
  return `class ${name}\n{\n${body}\n}`;
}

function propsFor(
  entity: EntityBlock,
  mode: Mode,
  validations: ValidationBlock[]
): Prop[] {
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declared = new Set(fields.map((f) => f.name));
  const out: Prop[] = [];

  if (mode === "full" && !declared.has("id")) {
    out.push({ name: "id", phpType: "string", nullable: false });
  }

  for (const field of fields) {
    const name = propertyName(field);
    const phpType = mapType(field.type);
    const isOptional =
      field.modifiers.some((m) => m.kind === "optional") ||
      (field.type.kind === "BelongsTo" && field.type.optional);
    const isRequired =
      (field.modifiers.some((m) => m.kind === "required") ||
        validationHas(validations, entity.name, field.name, "required")) &&
      !isOptional;

    if (mode === "update") {
      out.push({ name, phpType, nullable: true });
      continue;
    }

    if (mode === "full" && isOptional) {
      out.push({ name, phpType, nullable: true });
      continue;
    }

    if (mode === "create") {
      out.push({ name, phpType, nullable: !isRequired });
      continue;
    }

    out.push({ name, phpType, nullable: false });
  }

  if (mode === "full") {
    if (!declared.has("created_at")) {
      out.push({ name: "created_at", phpType: "string", nullable: false });
    }
    if (!declared.has("updated_at")) {
      out.push({ name: "updated_at", phpType: "string", nullable: false });
    }
    if (softDelete && !declared.has("deleted_at")) {
      out.push({ name: "deleted_at", phpType: "string", nullable: true });
    }
  }

  return out;
}

function propertyName(field: FieldDecl): string {
  if (field.type.kind === "BelongsTo") return fkColumnName(field.name);
  return toSnakeCase(field.name);
}

function mapType(type: TypeExpr): string {
  switch (type.kind) {
    case "Primitive":
      return mapPrimitive(type.name);
    case "Enum":
      return "string";
    case "BelongsTo":
    case "EntityRef":
      return "string";
  }
}

function mapPrimitive(name: PrimitiveType): string {
  switch (name) {
    case "string":
    case "text":
    case "phone":
    case "email":
    case "uuid":
    case "datetime":
    case "date":
      return "string";
    case "int":
      return "int";
    case "float":
      return "float";
    case "bool":
      return "bool";
    case "json":
      return "array";
  }
}

function validationHas(
  validations: ValidationBlock[],
  entity: string,
  field: string,
  mod: "required" | "unique"
): boolean {
  for (const block of validations) {
    if (block.entity !== entity) continue;
    for (const rule of block.rules) {
      if (rule.field === field && rule.modifiers.includes(mod)) return true;
    }
  }
  return false;
}
