import type {
  AipDocument,
  Duration,
  JobBlock,
  QueueBlock,
  Stmt,
  WorkflowBlock,
} from "@aiparlance/parser";

export class EmitWorkersError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitWorkersError";
  }
}

/**
 * Emit a TypeScript module with job stubs and queue names from Behavior AST.
 */
export function emitWorkers(doc: AipDocument): string {
  const jobs = doc.blocks.filter((b): b is JobBlock => b.kind === "Job");
  const queues = doc.blocks.filter((b): b is QueueBlock => b.kind === "Queue");
  const workflows = doc.blocks.filter(
    (b): b is WorkflowBlock => b.kind === "Workflow"
  );

  const dispatches = collectDispatches(workflows);

  const header = [
    `/** Generated by @aiparlance/workers from ${doc.fileName} — do not edit by hand. */`,
    `/** App: ${doc.app.name}${doc.app.version ? ` @${doc.app.version}` : ""} */`,
    "",
  ];

  if (jobs.length === 0 && queues.length === 0) {
    return [
      ...header,
      `// No job or queue blocks in this document.`,
      `// Declare \`job Name { ... }\` / \`queue Name\` (Behavior) and re-emit.`,
      `export {};`,
      "",
    ].join("\n");
  }

  const lines: string[] = [...header];

  if (queues.length > 0) {
    lines.push("/** Declared queue names. */");
    lines.push("export const queues = {");
    for (const q of queues) {
      lines.push(`  ${q.name}: ${JSON.stringify(q.name)},`);
    }
    lines.push("} as const;");
    lines.push("");
    lines.push("export type QueueName = (typeof queues)[keyof typeof queues];");
    lines.push("");
  }

  if (jobs.length > 0) {
    lines.push("/** Declared job names. */");
    lines.push("export const jobs = {");
    for (const j of jobs) {
      lines.push(`  ${j.name}: ${JSON.stringify(j.name)},`);
    }
    lines.push("} as const;");
    lines.push("");
    lines.push("export type JobName = (typeof jobs)[keyof typeof jobs];");
    lines.push("");

    for (const job of jobs) {
      const meta: string[] = [];
      if (job.retries != null) meta.push(`retries: ${job.retries}`);
      if (job.timeout) meta.push(`timeout: ${formatDuration(job.timeout)}`);
      const metaNote = meta.length > 0 ? ` (${meta.join(", ")})` : "";
      const from = dispatches
        .filter((d) => d.job === job.name)
        .map((d) => d.workflow);
      const dispatchNote =
        from.length > 0
          ? `\n * Dispatched from workflow(s): ${[...new Set(from)].join(", ")}.`
          : "";

      lines.push(`/**`);
      lines.push(` * Job stub: ${job.name}${metaNote}.${dispatchNote}`);
      lines.push(` * Wire your queue worker to call this handler.`);
      lines.push(` */`);
      lines.push(
        `export async function handle${job.name}(_payload: unknown): Promise<void> {`
      );
      lines.push(
        `  throw new Error(${JSON.stringify(`job ${job.name} not implemented`)});`
      );
      lines.push(`}`);
      lines.push("");
    }
  }

  if (dispatches.length > 0) {
    lines.push("/** Workflow → job dispatch edges (for wiring / docs). */");
    lines.push("export const dispatches = [");
    for (const d of dispatches) {
      const after = d.after
        ? `, after: ${JSON.stringify(formatDuration(d.after))}`
        : "";
      lines.push(
        `  { workflow: ${JSON.stringify(d.workflow)}, job: ${JSON.stringify(d.job)}${after} },`
      );
    }
    lines.push("] as const;");
    lines.push("");
  }

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function collectDispatches(
  workflows: WorkflowBlock[]
): Array<{ workflow: string; job: string; after: Duration | null }> {
  const out: Array<{ workflow: string; job: string; after: Duration | null }> =
    [];

  function walk(workflow: string, stmts: Stmt[]): void {
    for (const s of stmts) {
      if (s.kind === "dispatch") {
        out.push({ workflow, job: s.job, after: s.after });
      } else if (s.kind === "if") {
        walk(workflow, s.body);
      }
    }
  }

  for (const wf of workflows) walk(wf.name, wf.body);
  return out;
}

function formatDuration(d: Duration): string {
  return `${d.amount}${d.unit}`;
}
