import type {
  AipDocument,
  EntityBlock,
  FieldDecl,
  PrimitiveType,
  TypeExpr,
  ValidationBlock,
} from "@aiparlance/parser";
import { fkColumnName, tableName, toSnakeCase } from "@aiparlance/sql";

export class EmitGoError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmitGoError";
  }
}

type Mode = "full" | "create" | "update";

type FieldOut = {
  goName: string;
  jsonName: string;
  goType: string;
  required: boolean;
  /** Enum type name when this field introduced a typed string alias. */
  enumType?: string;
  enumVariants?: string[];
};

/**
 * Emit Go structs + thin net/http handlers from a Core AST.
 * Stdlib only (encoding/json, net/http, strings, time) — no framework lock-in.
 */
export function emitGo(doc: AipDocument): string {
  const entities = doc.blocks.filter(
    (b): b is EntityBlock => b.kind === "Entity"
  );
  if (entities.length === 0) {
    throw new EmitGoError("no entity blocks to emit");
  }

  const crudEntities = new Set(
    doc.blocks
      .filter((b) => b.kind === "Crud")
      .map((b) => (b.kind === "Crud" ? b.entity : ""))
  );

  const validations = doc.blocks.filter(
    (b): b is ValidationBlock => b.kind === "Validation"
  );

  const auth = doc.app.members.find((m) => m.kind === "auth");
  const needsHttp = crudEntities.size > 0 || Boolean(auth);
  const needsTime = true; // implicit timestamps on every entity
  const needsJson =
    needsHttp ||
    entities.some((e) =>
      e.body.some(
        (b) =>
          b.kind === "Field" &&
          b.type.kind === "Primitive" &&
          b.type.name === "json"
      )
    );
  const needsStrings = Boolean(auth);

  const pkg = packageName(doc.app.name);
  const lines: string[] = [
    `// Code generated by @aiparlance/go from ${doc.fileName}; DO NOT EDIT.`,
    "",
    `package ${pkg}`,
    "",
  ];

  const imports: string[] = [];
  if (needsJson) imports.push('"encoding/json"');
  if (needsHttp) imports.push('"net/http"');
  if (needsStrings) imports.push('"strings"');
  if (needsTime) imports.push('"time"');

  if (imports.length === 1) {
    lines.push(`import ${imports[0]}`, "");
  } else if (imports.length > 1) {
    lines.push("import (");
    for (const imp of imports) lines.push(`\t${imp}`);
    lines.push(")", "");
  }

  const enumDecls = new Map<string, string[]>();
  const emittedEnums = new Set<string>();

  for (const entity of entities) {
    const full = fieldsFor(entity, "full", validations, enumDecls);
    const create = fieldsFor(entity, "create", validations, enumDecls);
    const update = fieldsFor(entity, "update", validations, enumDecls);

    for (const [typeName, variants] of enumDecls) {
      if (emittedEnums.has(typeName)) continue;
      emittedEnums.add(typeName);
      lines.push(`type ${typeName} string`, "");
      lines.push("const (");
      for (const v of variants) {
        lines.push(
          `\t${typeName}${toPascal(v)} ${typeName} = ${JSON.stringify(v)}`
        );
      }
      lines.push(")", "");
    }

    lines.push(emitStruct(entity.name, full));
    lines.push("");
    lines.push(emitStruct(`${entity.name}Create`, create));
    lines.push("");
    lines.push(emitStruct(`${entity.name}Update`, update));
    lines.push("");

    if (crudEntities.has(entity.name)) {
      lines.push(...emitCrud(entity));
      lines.push("");
    }
  }

  if (auth && auth.kind === "auth") {
    lines.push(...emitAuthMiddleware(auth.strategy));
    lines.push("");
  }

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function packageName(appName: string): string {
  const raw = appName.toLowerCase().replace(/[^a-z0-9]+/g, "");
  if (!raw || /^[0-9]/.test(raw)) return "aiparlance";
  return raw;
}

function fieldsFor(
  entity: EntityBlock,
  mode: Mode,
  validations: ValidationBlock[],
  enumDecls: Map<string, string[]>
): FieldOut[] {
  const softDelete = entity.body.some((m) => m.kind === "soft_delete");
  const fields = entity.body.filter((b): b is FieldDecl => b.kind === "Field");
  const declared = new Set(fields.map((f) => f.name));
  const out: FieldOut[] = [];

  if (mode === "full" && !declared.has("id")) {
    out.push({
      goName: "ID",
      jsonName: "id",
      goType: "string",
      required: true,
    });
  }

  for (const field of fields) {
    const jsonName = propertyName(field);
    const goName = toPascal(jsonName);
    const mapped = mapType(field.type, entity.name, goName, enumDecls);
    const isOptional =
      field.modifiers.some((m) => m.kind === "optional") ||
      (field.type.kind === "BelongsTo" && field.type.optional);
    const isRequired =
      (field.modifiers.some((m) => m.kind === "required") ||
        validationHas(validations, entity.name, field.name, "required")) &&
      !isOptional;

    if (mode === "update") {
      out.push({
        goName,
        jsonName,
        goType: `*${mapped.goType}`,
        required: false,
        enumType: mapped.enumType,
        enumVariants: mapped.enumVariants,
      });
      continue;
    }

    if (mode === "full" && isOptional) {
      out.push({
        goName,
        jsonName,
        goType: `*${mapped.goType}`,
        required: false,
        enumType: mapped.enumType,
        enumVariants: mapped.enumVariants,
      });
      continue;
    }

    const required = mode === "create" || mode === "full" ? isRequired : false;
    out.push({
      goName,
      jsonName,
      goType:
        !required && mode === "create"
          ? `*${mapped.goType}`
          : mapped.goType,
      required,
      enumType: mapped.enumType,
      enumVariants: mapped.enumVariants,
    });
  }

  if (mode === "full") {
    if (!declared.has("created_at")) {
      out.push({
        goName: "CreatedAt",
        jsonName: "created_at",
        goType: "time.Time",
        required: true,
      });
    }
    if (!declared.has("updated_at")) {
      out.push({
        goName: "UpdatedAt",
        jsonName: "updated_at",
        goType: "time.Time",
        required: true,
      });
    }
    if (softDelete && !declared.has("deleted_at")) {
      out.push({
        goName: "DeletedAt",
        jsonName: "deleted_at",
        goType: "*time.Time",
        required: false,
      });
    }
  }

  return out;
}

function emitStruct(name: string, fields: FieldOut[]): string {
  const nameWidth = Math.max(...fields.map((f) => f.goName.length), 1);
  const typeWidth = Math.max(...fields.map((f) => f.goType.length), 1);
  const body = fields
    .map((f) => {
      const tag = f.required
        ? `json:"${f.jsonName}"`
        : `json:"${f.jsonName},omitempty"`;
      const n = f.goName.padEnd(nameWidth);
      const t = f.goType.padEnd(typeWidth);
      return `\t${n} ${t} \`${tag}\``;
    })
    .join("\n");
  return `type ${name} struct {\n${body}\n}`;
}

function emitCrud(entity: EntityBlock): string[] {
  const collection = `/${tableName(entity.name)}`;
  const constName = `${entity.name}Collection`;
  const lines: string[] = [
    `// Thin CRUD helpers for ${entity.name} (stdlib net/http; wire your store).`,
    `const ${constName} = ${JSON.stringify(collection)}`,
    "",
    `func ${entity.name}Item(id string) string {`,
    `\treturn ${constName} + "/" + id`,
    `}`,
    "",
    `func List${entity.name}(w http.ResponseWriter, r *http.Request) {`,
    `\tw.Header().Set("Content-Type", "application/json")`,
    `\tw.WriteHeader(http.StatusNotImplemented)`,
    `\t_ = json.NewEncoder(w).Encode(map[string]string{"error": "not implemented"})`,
    `}`,
    "",
    `func Create${entity.name}(w http.ResponseWriter, r *http.Request) {`,
    `\tvar in ${entity.name}Create`,
    `\tif err := json.NewDecoder(r.Body).Decode(&in); err != nil {`,
    `\t\thttp.Error(w, "bad request", http.StatusBadRequest)`,
    `\t\treturn`,
    `\t}`,
    `\t_ = in`,
    `\tw.Header().Set("Content-Type", "application/json")`,
    `\tw.WriteHeader(http.StatusNotImplemented)`,
    `\t_ = json.NewEncoder(w).Encode(map[string]string{"error": "not implemented"})`,
    `}`,
    "",
    `func Get${entity.name}(w http.ResponseWriter, r *http.Request) {`,
    `\tw.Header().Set("Content-Type", "application/json")`,
    `\tw.WriteHeader(http.StatusNotImplemented)`,
    `\t_ = json.NewEncoder(w).Encode(map[string]string{"error": "not implemented"})`,
    `}`,
    "",
    `func Update${entity.name}(w http.ResponseWriter, r *http.Request) {`,
    `\tvar in ${entity.name}Update`,
    `\tif err := json.NewDecoder(r.Body).Decode(&in); err != nil {`,
    `\t\thttp.Error(w, "bad request", http.StatusBadRequest)`,
    `\t\treturn`,
    `\t}`,
    `\t_ = in`,
    `\tw.Header().Set("Content-Type", "application/json")`,
    `\tw.WriteHeader(http.StatusNotImplemented)`,
    `\t_ = json.NewEncoder(w).Encode(map[string]string{"error": "not implemented"})`,
    `}`,
    "",
    `func Delete${entity.name}(w http.ResponseWriter, r *http.Request) {`,
    `\tw.WriteHeader(http.StatusNotImplemented)`,
    `}`,
  ];
  return lines;
}

function emitAuthMiddleware(
  strategy: "jwt" | "session" | "api_key" | "oauth"
): string[] {
  switch (strategy) {
    case "jwt":
    case "oauth":
      return [
        `// AuthMiddleware checks a Bearer token is present (validate signature in your app).`,
        `func AuthMiddleware(next http.Handler) http.Handler {`,
        `\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {`,
        `\t\tauth := r.Header.Get("Authorization")`,
        `\t\tif !strings.HasPrefix(auth, "Bearer ") || len(strings.TrimSpace(auth[7:])) == 0 {`,
        `\t\t\thttp.Error(w, "unauthorized", http.StatusUnauthorized)`,
        `\t\t\treturn`,
        `\t\t}`,
        `\t\tnext.ServeHTTP(w, r)`,
        `\t})`,
        `}`,
      ];
    case "api_key":
      return [
        `// AuthMiddleware checks the X-API-Key header is present.`,
        `func AuthMiddleware(next http.Handler) http.Handler {`,
        `\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {`,
        `\t\tif strings.TrimSpace(r.Header.Get("X-API-Key")) == "" {`,
        `\t\t\thttp.Error(w, "unauthorized", http.StatusUnauthorized)`,
        `\t\t\treturn`,
        `\t\t}`,
        `\t\tnext.ServeHTTP(w, r)`,
        `\t})`,
        `}`,
      ];
    case "session":
      return [
        `// AuthMiddleware checks a session cookie is present.`,
        `func AuthMiddleware(next http.Handler) http.Handler {`,
        `\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {`,
        `\t\tc, err := r.Cookie("session")`,
        `\t\tif err != nil || strings.TrimSpace(c.Value) == "" {`,
        `\t\t\thttp.Error(w, "unauthorized", http.StatusUnauthorized)`,
        `\t\t\treturn`,
        `\t\t}`,
        `\t\tnext.ServeHTTP(w, r)`,
        `\t})`,
        `}`,
      ];
  }
}

function propertyName(field: FieldDecl): string {
  if (field.type.kind === "BelongsTo") return fkColumnName(field.name);
  return toSnakeCase(field.name);
}

function mapType(
  type: TypeExpr,
  entityName: string,
  fieldGoName: string,
  enumDecls: Map<string, string[]>
): { goType: string; enumType?: string; enumVariants?: string[] } {
  switch (type.kind) {
    case "Primitive":
      return { goType: mapPrimitive(type.name) };
    case "Enum": {
      const typeName = `${entityName}${fieldGoName}`;
      enumDecls.set(typeName, type.variants);
      return {
        goType: typeName,
        enumType: typeName,
        enumVariants: type.variants,
      };
    }
    case "BelongsTo":
    case "EntityRef":
      return { goType: "string" };
  }
}

function mapPrimitive(name: PrimitiveType): string {
  switch (name) {
    case "string":
    case "text":
    case "phone":
    case "email":
    case "uuid":
      return "string";
    case "int":
      return "int64";
    case "float":
      return "float64";
    case "bool":
      return "bool";
    case "datetime":
    case "date":
      return "time.Time";
    case "json":
      return "json.RawMessage";
  }
}

function validationHas(
  validations: ValidationBlock[],
  entity: string,
  field: string,
  mod: "required" | "unique"
): boolean {
  for (const block of validations) {
    if (block.entity !== entity) continue;
    for (const rule of block.rules) {
      if (rule.field === field && rule.modifiers.includes(mod)) return true;
    }
  }
  return false;
}

/** snake_case or kebab → PascalCase; trailing `id` → `ID`. */
function toPascal(name: string): string {
  const parts = name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  return parts
    .map((p, i) => {
      const lower = p.toLowerCase();
      if (lower === "id" && i === parts.length - 1) return "ID";
      return p.charAt(0).toUpperCase() + p.slice(1);
    })
    .join("");
}
